// GENERATED by scripts/genSolverCoverage.mjs — do not edit by hand.
// Regenerate with `npm run gen:coverage`; `solverCoverage.test.ts` fails if
// this file goes stale, so a solver test cannot be added or renamed without the
// /validation page noticing.
//
// Inventory of every vitest case that exercises a SOLVER engine — a module that
// computes a structural response (assembles and solves equilibrium, an
// eigenproblem, or a time/path integration), plus the bridge feeding them.
// Design checks, load generation, geotech and quantities are covered instead by
// the hand-calc benchmarks in `validation.ts`.
//
// These names are read from the test sources. Nothing here observes a pass
// state: what the page claims is that these cases exist and that CI runs them.
import type { SolverGroup } from './solverCoverageParse'

export interface SolverTest { suite: string; name: string }
export interface SolverModuleCoverage {
  /** Engine module, i.e. `engine/<module>.ts`. */
  module: string
  group: SolverGroup
  /** What the module solves. */
  title: string
  /** True when the file exercises several solvers together rather than one
   *  module — there is no `engine/<module>.ts` behind it. */
  integration: boolean
  tests: SolverTest[]
}

/** Total solver-engine cases in the manifest. */
export const SOLVER_TEST_COUNT = 492

export const SOLVER_COVERAGE: SolverModuleCoverage[] = [
  {
    "module": "modelBridge",
    "group": "Bridge",
    "title": "StructuralModel → solver input",
    "integration": false,
    "tests": [
      {
        "suite": "modelToFrame3D — rigid offsets",
        "name": "maps member offsets to F3Member offI / offJ"
      },
      {
        "suite": "modelToFrame3D — rigid offsets",
        "name": "omits offI / offJ when no offsets are set"
      },
      {
        "suite": "modelToFrame3D — rigid offsets",
        "name": "applies auto rigid end zones when rigidEndZones is on"
      },
      {
        "suite": "modelToFrame3D — rigid offsets",
        "name": "manual offsets take precedence over auto rigid zones"
      },
      {
        "suite": "modelToFrame3D — cracked-section modifiers (ACI 318-14 §6.6.3.1.1)",
        "name": "default (opt-out) keeps gross section properties"
      },
      {
        "suite": "modelToFrame3D — cracked-section modifiers (ACI 318-14 §6.6.3.1.1)",
        "name": "crackedSections: beams 0.35Ig, columns 0.70Ig, both axes; A and J gross"
      },
      {
        "suite": "modelToFrame3D — cracked-section modifiers (ACI 318-14 §6.6.3.1.1)",
        "name": "steel members are exempt from cracking factors"
      },
      {
        "suite": "modelToFrame3D — cracked-section modifiers (ACI 318-14 §6.6.3.1.1)",
        "name": "cracked beam deflects 1/0.35× more under the same load (bridge → solver)"
      },
      {
        "suite": "modelToFrame3D — shell elements",
        "name": "meshes each panel into two triangular shells when shellElements is on"
      },
      {
        "suite": "modelToFrame3D — shell elements",
        "name": "produces no shells (classic tributary path) when the flag is off"
      },
      {
        "suite": "modelToFrame3D — shell elements",
        "name": "routes the panel area load to corner nodes (−Y) and skips tributary — no double count"
      },
      {
        "suite": "modelToFrame3D — shell elements",
        "name": "useShells:false overrides the model flag (keeps tributary for design)"
      },
      {
        "suite": "modelToFrame3D — member-thermal loads",
        "name": "converts EA·α·ΔT to kN (hand calc: 300×500 f'c=28, α=1e-5, ΔT=20 → ≈746 kN)"
      },
      {
        "suite": "connection type → member releases (force behaviour)",
        "name": "a 'simple' end releases the bending moments My, Mz (a pin)"
      },
      {
        "suite": "connection type → member releases (force behaviour)",
        "name": "'moment' and 'fixed' ends stay continuous (no release)"
      },
      {
        "suite": "connection type → member releases (force behaviour)",
        "name": "explicit releases are unioned with connection-implied ones"
      },
      {
        "suite": "connection type → member releases (force behaviour)",
        "name": "the bridge pins a simple-ended beam in the assembled frame"
      },
      {
        "suite": "bridge → solver unit contract (absolute closed forms)",
        "name": "nodal kN load → δ = PL³/3EI in metres (E MPa · I mm⁴ · L m all consistent)"
      },
      {
        "suite": "bridge → solver unit contract (absolute closed forms)",
        "name": "member UDL in kN/m → ΣR = w·L kN and fixed-end moment wL²/2 at the root"
      },
      {
        "suite": "bridge → solver unit contract (absolute closed forms)",
        "name": "member point load kN at t → ΣR equals P (no unit slip in the a=t·L mapping)"
      },
      {
        "suite": "bridge → solver unit contract (absolute closed forms)",
        "name": "restrained thermal force is E·A·α·ΔT/1000 kN — the PR #319 contract"
      },
      {
        "suite": "bridge → solver unit contract (absolute closed forms)",
        "name": "spring support: reaction = −k·d with k in kN/m, d in m"
      },
      {
        "suite": "modelToFrame3D — Timoshenko shear areas (opt-in)",
        "name": "off by default: members carry no Asy/Asz (Euler benchmarks anchored)"
      },
      {
        "suite": "modelToFrame3D — Timoshenko shear areas (opt-in)",
        "name": "concrete rectangle: Asy = Asz = 5/6·b·h"
      },
      {
        "suite": "modelToFrame3D — Timoshenko shear areas (opt-in)",
        "name": "steel W-shape: Asy = d·tw (AISC §G2.1 web), Asz = 5/6·2·bf·tf (flanges)"
      },
      {
        "suite": "modelToFrame3D — Timoshenko shear areas (opt-in)",
        "name": "shear-deformable solve is softer than Euler and keeps ΣR = ΣP"
      }
    ]
  },
  {
    "module": "rigidEndZones",
    "group": "Bridge",
    "title": "Rigid end zones / member offsets",
    "integration": false,
    "tests": [
      {
        "suite": "autoRigidOffsets",
        "name": "returns an empty map for factor ≤ 0"
      },
      {
        "suite": "autoRigidOffsets",
        "name": "beam gets an inward i-end offset = factor·(column DEPTH/2) along +X (ETABS face offset)"
      },
      {
        "suite": "autoRigidOffsets",
        "name": "a Z-girder at the same joint gets the column WIDTH/2 (weak-direction face)"
      },
      {
        "suite": "autoRigidOffsets",
        "name": "column gets an inward j-end offset = factor·(beam depth/2) along +Y"
      },
      {
        "suite": "autoRigidOffsets",
        "name": "scales linearly with the rigid-zone factor"
      },
      {
        "suite": "autoRigidOffsets",
        "name": "per-member rigidZoneFactor overrides the model factor (0 excludes the member)"
      },
      {
        "suite": "autoRigidOffsets",
        "name": "resolves steel AISC shape dimensions, not the bounding-box b/h"
      },
      {
        "suite": "autoRigidOffsets",
        "name": "caps the total offset so the clear span stays positive"
      }
    ]
  },
  {
    "module": "diaphragm",
    "group": "Bridge",
    "title": "Rigid floor diaphragm constraints",
    "integration": false,
    "tests": [
      {
        "suite": "buildDiaphragmGroups — rigid floor diaphragm node grouping",
        "name": "returns no groups when the model has no storeys"
      },
      {
        "suite": "buildDiaphragmGroups — rigid floor diaphragm node grouping",
        "name": "groups all nodes at a storey elevation: first = master, rest = slaves"
      },
      {
        "suite": "buildDiaphragmGroups — rigid floor diaphragm node grouping",
        "name": "skips storeys with fewer than 2 nodes at that elevation (nothing to tie)"
      },
      {
        "suite": "buildDiaphragmGroups — rigid floor diaphragm node grouping",
        "name": "produces one group per storey in a multi-storey model"
      },
      {
        "suite": "buildDiaphragmGroups — rigid floor diaphragm node grouping",
        "name": "matches elevations within the tolerance but not beyond it"
      }
    ]
  },
  {
    "module": "fem",
    "group": "FEM solver",
    "title": "Linear-algebra core (LU factor / solve)",
    "integration": false,
    "tests": [
      {
        "suite": "solveLinear — Gaussian elimination with partial pivoting",
        "name": "solves a 1×1 system"
      },
      {
        "suite": "solveLinear — Gaussian elimination with partial pivoting",
        "name": "solves a 2×2 diagonal system"
      },
      {
        "suite": "solveLinear — Gaussian elimination with partial pivoting",
        "name": "solves a 3×3 system"
      },
      {
        "suite": "solveLinear — Gaussian elimination with partial pivoting",
        "name": "returns null for a singular matrix"
      },
      {
        "suite": "solveLinear — Gaussian elimination with partial pivoting",
        "name": "A·x = b round-trip"
      },
      {
        "suite": "luFactor / luSolve — LU factorisation with multiple-RHS solves",
        "name": "returns {n:0} for an empty matrix"
      },
      {
        "suite": "luFactor / luSolve — LU factorisation with multiple-RHS solves",
        "name": "factors and solves a 1×1 system"
      },
      {
        "suite": "luFactor / luSolve — LU factorisation with multiple-RHS solves",
        "name": "factors and solves a 2×2 system"
      },
      {
        "suite": "luFactor / luSolve — LU factorisation with multiple-RHS solves",
        "name": "solves the same 3×3 system as solveLinear"
      },
      {
        "suite": "luFactor / luSolve — LU factorisation with multiple-RHS solves",
        "name": "returns null for a singular matrix"
      },
      {
        "suite": "luFactor / luSolve — LU factorisation with multiple-RHS solves",
        "name": "reuses one factorisation for two different RHS"
      },
      {
        "suite": "luFactor / luSolve — LU factorisation with multiple-RHS solves",
        "name": "matches solveLinear on a 4×4 symmetric positive-definite system"
      },
      {
        "suite": "matVec — matrix-vector product",
        "name": "identity matrix returns the same vector"
      },
      {
        "suite": "matVec — matrix-vector product",
        "name": "2×2 product"
      },
      {
        "suite": "hermite — Hermite cubic shape functions",
        "name": "partition of unity at ξ=0: N1=1, N2=N3=N4=0"
      },
      {
        "suite": "hermite — Hermite cubic shape functions",
        "name": "partition at ξ=1: N3=1, N1=N2=N4=0"
      },
      {
        "suite": "hermite — Hermite cubic shape functions",
        "name": "midpoint ξ=0.5: N1=N3=0.5, N2=le/8, N4=−le/8"
      },
      {
        "suite": "hermite — Hermite cubic shape functions",
        "name": "N1 + N3 = 1 everywhere (displacement completeness)"
      },
      {
        "suite": "gauss5Vec — 5-point Gauss quadrature",
        "name": "integrates a constant exactly"
      },
      {
        "suite": "gauss5Vec — 5-point Gauss quadrature",
        "name": "integrates a linear function exactly"
      },
      {
        "suite": "gauss5Vec — 5-point Gauss quadrature",
        "name": "integrates a cubic polynomial exactly"
      },
      {
        "suite": "gauss5Vec — 5-point Gauss quadrature",
        "name": "handles a vector-valued integrand"
      }
    ]
  },
  {
    "module": "frame2d",
    "group": "FEM solver",
    "title": "Plane frame",
    "integration": false,
    "tests": [
      {
        "suite": "frame2d — regression vs the beam solver",
        "name": "horizontal member, SS + UDL: reactions wL/2, member Mmax = wL²/8"
      },
      {
        "suite": "frame2d — regression vs the beam solver",
        "name": "midspan point load: Mmax = PL/4, matches solveFEM"
      },
      {
        "suite": "frame2d — orientation (vertical members)",
        "name": "cantilever column + horizontal tip load: δ = PL³/3EI, Mbase = PL"
      },
      {
        "suite": "frame2d — orientation (vertical members)",
        "name": "axial column: δ = PL/EA, N = −P (compression)"
      },
      {
        "suite": "frame2d — portal frame",
        "name": "pinned-base portal with beam UDL: equilibrium + symmetry"
      },
      {
        "suite": "frame2d — NSCP combinations",
        "name": "runs all 7; 1.2D + 1.6L governs for D+L loading"
      }
    ]
  },
  {
    "module": "frame3d",
    "group": "FEM solver",
    "title": "12-DOF space frame",
    "integration": false,
    "tests": [
      {
        "suite": "frame3d — closed forms (cantilever along x, L = 3)",
        "name": "tip gravity point (−Y): δy = PL³/3EIz, Mz,base = PL"
      },
      {
        "suite": "frame3d — closed forms (cantilever along x, L = 3)",
        "name": "tip lateral nodal load (−Z): δz = PL³/3EIy, My,base = PL (second plane)"
      },
      {
        "suite": "frame3d — closed forms (cantilever along x, L = 3)",
        "name": "gravity UDL: Mz,base = wL²/2, δtip = wL⁴/8EIz"
      },
      {
        "suite": "frame3d — closed forms (cantilever along x, L = 3)",
        "name": "tip torque Mx: θx = TL/GJ, T constant"
      },
      {
        "suite": "frame3d — closed forms (cantilever along x, L = 3)",
        "name": "axial nodal load (+X): δx = PL/EA"
      },
      {
        "suite": "frame3d — square-section J",
        "name": "rectJ(square) ≈ 0.1406·b⁴"
      },
      {
        "suite": "frame3d — planar portal matches frame2d",
        "name": "fixed-base portal with beam UDL: same reactions and beam Mmax"
      },
      {
        "suite": "frame3d — full model bridge (grid + slab loads)",
        "name": "slab area load reaches the supports: ΣRy = factored q·A under 1.4D"
      },
      {
        "suite": "frame3d — full model bridge (grid + slab loads)",
        "name": "two-storey grid solves and distributes both categories"
      },
      {
        "suite": "frame3d — P-Δ second order (vertical cantilever, L = 4)",
        "name": "compression amplifies drift ≈ 1/(1−P/Pe) and converges"
      },
      {
        "suite": "frame3d — P-Δ second order (vertical cantilever, L = 4)",
        "name": "tension stiffens the column (drift below first order)"
      },
      {
        "suite": "frame3d — P-Δ second order (vertical cantilever, L = 4)",
        "name": "negligible axial → P-Δ collapses to the first-order result"
      },
      {
        "suite": "frame3d — P-Δ second order (vertical cantilever, L = 4)",
        "name": "base moment is amplified in step with the drift"
      },
      {
        "suite": "frame3d — P-Δ second order (vertical cantilever, L = 4)",
        "name": "fixedAxial builds a CONSTANT geometric tangent (lateral-only solve, linear in load)"
      },
      {
        "suite": "frame3d — P-Δ second order (vertical cantilever, L = 4)",
        "name": "iterative P-Δ surfaces {converged, iterations, residual} on the result"
      },
      {
        "suite": "frame3d — P-Δ second order (vertical cantilever, L = 4)",
        "name": "P-Δ base reaction carries the secondary moment: M_base ≈ H·L + P·Δ"
      },
      {
        "suite": "frame3d — P-Δ second order (vertical cantilever, L = 4)",
        "name": "P-Δ that runs out of iterations reports converged:false, not a silent pass"
      },
      {
        "suite": "frame3d — P-Δ second order (vertical cantilever, L = 4)",
        "name": "fixedAxial tension stiffens; amplification grows without bound toward Pcr"
      },
      {
        "suite": "serializePrecomp / deserializePrecomp — postMessage roundtrip",
        "name": "roundtrip preserves all scalar fields"
      },
      {
        "suite": "serializePrecomp / deserializePrecomp — postMessage roundtrip",
        "name": "freeIdx Map is reconstructed correctly"
      },
      {
        "suite": "serializePrecomp / deserializePrecomp — postMessage roundtrip",
        "name": "solveWithGeometry gives identical results on the deserialized precomp"
      },
      {
        "suite": "frame3d — member end releases",
        "name": "no releases: end moments = wL²/12 (fixed-fixed)"
      },
      {
        "suite": "frame3d — member end releases",
        "name": "Mz released at both ends (→ simply supported): end moments ≈ 0, midspan = wL²/8"
      },
      {
        "suite": "frame3d — member end releases",
        "name": "Mz released at i-end (→ propped cantilever): Mj = wL²/8, Ri = 3wL/8"
      },
      {
        "suite": "frame3d — member end releases",
        "name": "beam in portal frame with Mz releases at beam-column joints"
      },
      {
        "suite": "frame3d — spring supports",
        "name": "cantilever tip spring: δy = Fy / (k_beam + k_spring)"
      },
      {
        "suite": "frame3d — spring supports",
        "name": "spring reaction opposes displacement (restoring force sign)"
      },
      {
        "suite": "frame3d — spring supports",
        "name": "spring carries only a share of the load (beam stiffness >> spring stiffness here)"
      },
      {
        "suite": "appliedResultant — statics self-check (§8)",
        "name": "sums node loads per global axis"
      },
      {
        "suite": "appliedResultant — statics self-check (§8)",
        "name": "integrates member gravity loads (UDL w·L, VDL ½(w1+w2)·Δ, point P) into −Y"
      },
      {
        "suite": "appliedResultant — statics self-check (§8)",
        "name": "balances the reactions for a slab-loaded grid: ΣApplied + ΣReactions ≈ 0"
      },
      {
        "suite": "rigid floor diaphragm — precomputeFrame + solveWithGeometry",
        "name": "without diaphragm: left column takes all sway (right column uninvited)"
      },
      {
        "suite": "rigid floor diaphragm — precomputeFrame + solveWithGeometry",
        "name": "with diaphragm: both column tops have equal Ux"
      },
      {
        "suite": "rigid floor diaphragm — precomputeFrame + solveWithGeometry",
        "name": "with diaphragm: arm effect — slave at dz offset shares θy with master"
      },
      {
        "suite": "rigid links / member offsets — Teff = T·H",
        "name": "zero offset is identical to no offset (cantilever closed form)"
      },
      {
        "suite": "rigid links / member offsets — Teff = T·H",
        "name": "rigid offset arm matches an explicit near-rigid stub member"
      },
      {
        "suite": "rigid links / member offsets — Teff = T·H",
        "name": "global equilibrium holds with an offset (ΣReactions + ΣApplied = 0)"
      },
      {
        "suite": "frame3d — local-axis rotation (ETABS local axis 2 angle)",
        "name": "localAxes(dir, 90) turns a vertical member’s depth axis onto global X"
      },
      {
        "suite": "frame3d — local-axis rotation (ETABS local axis 2 angle)",
        "name": "rotating a non-square vertical cantilever 90° swaps its strong/weak response"
      },
      {
        "suite": "frame3d — local-axis rotation (ETABS local axis 2 angle)",
        "name": "the bridge defaults vertical members to rot 90 and honors an explicit value"
      },
      {
        "suite": "frame3d — Timoshenko shear deformation (Φ = 12EI/(G·As·L²))",
        "name": "tip load (−Y): δ = PL³/3EIz + PL/GAsy — the 2-node element is nodally exact"
      },
      {
        "suite": "frame3d — Timoshenko shear deformation (Φ = 12EI/(G·As·L²))",
        "name": "second plane (−Z): δ = PL³/3EIy + PL/GAsz"
      },
      {
        "suite": "frame3d — Timoshenko shear deformation (Φ = 12EI/(G·As·L²))",
        "name": "shear share is significant for a squat member and vanishes for a slender one"
      },
      {
        "suite": "frame3d — Timoshenko shear deformation (Φ = 12EI/(G·As·L²))",
        "name": "omitted shear areas keep the classic Euler element (regression anchor)"
      },
      {
        "suite": "frame3d — Timoshenko shear deformation (Φ = 12EI/(G·As·L²))",
        "name": "fixed-fixed centre load across two elements: δ = PL³/192EI + PL/4GAs"
      }
    ]
  },
  {
    "module": "shell",
    "group": "FEM solver",
    "title": "CST + DKT flat shell",
    "integration": false,
    "tests": [
      {
        "suite": "triFrame",
        "name": "builds a right-handed local frame with n1 at origin and n2 on +x̂"
      },
      {
        "suite": "triFrame",
        "name": "handles a tilted (X-Z plane) triangle — area is orientation-independent"
      },
      {
        "suite": "element stiffness sanity",
        "name": "membrane & bending stiffness are symmetric"
      },
      {
        "suite": "element stiffness sanity",
        "name": "a rigid-body motion produces zero element forces"
      },
      {
        "suite": "membrane (CST) — constant-strain exactness",
        "name": "uniaxial tension reproduces ε = σ/E exactly"
      },
      {
        "suite": "DKT plate bending — Timoshenko benchmarks",
        "name": "simply-supported square plate central deflection ≈ 0.00406 q L⁴/D"
      },
      {
        "suite": "DKT plate bending — Timoshenko benchmarks",
        "name": "clamped square plate central deflection ≈ 0.00126 q L⁴/D"
      },
      {
        "suite": "DKT plate bending — Timoshenko benchmarks",
        "name": "converges toward the analytical value as the mesh refines"
      },
      {
        "suite": "orientation independence",
        "name": "an X-Z-plane plate gives the same central deflection as an X-Y-plane plate"
      },
      {
        "suite": "dktBmat",
        "name": "integrating Bᵀ D B over the 3 mid-edge Gauss points reproduces dktBending K"
      },
      {
        "suite": "recoverShellStress",
        "name": "recovers σx ≈ σ_applied on the axis-aligned element (e0 local frame = global)"
      },
      {
        "suite": "recoverShellStress",
        "name": "σ1 ≥ σ2 and vonMises ≥ 0 for all elements"
      },
      {
        "suite": "recoverShellStress",
        "name": "bending moments ≈ 0 for a pure in-plane load"
      },
      {
        "suite": "recoverShellStress",
        "name": "bending moments non-zero under out-of-plane pressure (coarser mesh with interior node)"
      },
      {
        "suite": "shellNodalContour",
        "name": "returns a value for every node"
      },
      {
        "suite": "shellNodalContour",
        "name": "all values finite and non-negative for vonMises"
      },
      {
        "suite": "bilinearQuad",
        "name": "reproduces the four corners at the parametric corners"
      },
      {
        "suite": "bilinearQuad",
        "name": "gives the centroid at (½,½) and edge midpoints"
      },
      {
        "suite": "subdivideQuadPlates",
        "name": "n = 1 reproduces the 2-triangle, 4-node quad"
      },
      {
        "suite": "subdivideQuadPlates",
        "name": "n = 4 yields (n+1)² nodes and 2n² triangles"
      },
      {
        "suite": "subdivideQuadPlates",
        "name": "adjacent plates share the common-edge nodes (conforming mesh)"
      },
      {
        "suite": "subdivideQuadPlates",
        "name": "cornerId reuses existing model node ids at coincident positions"
      },
      {
        "suite": "subdivideQuadPlates",
        "name": "refining the subdivision converges a simply-supported plate toward Timoshenko"
      }
    ]
  },
  {
    "module": "frame3dShell",
    "group": "FEM solver",
    "title": "Frame ↔ shell coupling",
    "integration": true,
    "tests": [
      {
        "suite": "frame3d shell integration",
        "name": "matches the standalone solveShell displacements (same elements & loads)"
      },
      {
        "suite": "frame3d shell integration",
        "name": "reactions balance the applied load (ΣFz = +6 kN up)"
      },
      {
        "suite": "frame3d shell integration",
        "name": "a shell stiffens a frame model — combined tip deflection < bare beam"
      },
      {
        "suite": "frame3d shell integration",
        "name": "no shells → identical result to the pre-shell solver (backward compatible)"
      },
      {
        "suite": "frame3d shell integration",
        "name": "serializes shell geometry across the worker boundary"
      }
    ]
  },
  {
    "module": "shellModel",
    "group": "FEM solver",
    "title": "Shell meshing from the model",
    "integration": false,
    "tests": [
      {
        "suite": "meshModelShells",
        "name": "reuses the model corner node ids and meshes n×n cells"
      },
      {
        "suite": "solveModelShells",
        "name": "returns null when the model has no plates"
      },
      {
        "suite": "solveModelShells",
        "name": "recovers a non-trivial bending field under area load"
      },
      {
        "suite": "solveModelShells",
        "name": "factored field scales linearly with the load factors"
      },
      {
        "suite": "designModelSlabsFE — Wood-Armer reinforcement from the FE field",
        "name": "designs one row per slab with positive reinforcement"
      },
      {
        "suite": "designModelSlabsFE — Wood-Armer reinforcement from the FE field",
        "name": "uses the NSCP 1.2D + 1.6L factored field by default (heavier than service)"
      },
      {
        "suite": "designModelSlabsFE — Wood-Armer reinforcement from the FE field",
        "name": "factored design never needs less steel than the service field"
      },
      {
        "suite": "designModelSlabsFE — Wood-Armer reinforcement from the FE field",
        "name": "skips wall panels"
      }
    ]
  },
  {
    "module": "modal",
    "group": "Dynamics",
    "title": "Eigenvalue / mode extraction",
    "integration": false,
    "tests": [
      {
        "suite": "jacobiEigen — symmetric eigen-decomposition",
        "name": "diagonalises a diagonal matrix"
      },
      {
        "suite": "jacobiEigen — symmetric eigen-decomposition",
        "name": "matches the closed-form eigenpairs of [[2,1],[1,2]]"
      },
      {
        "suite": "jacobiEigen — symmetric eigen-decomposition",
        "name": "returns eigenvectors of unit length"
      },
      {
        "suite": "jacobiEigen — 2-storey shear building (textbook closed form)",
        "name": "eigenvalues are k·(3 ∓ √5)/2 for m = 1"
      },
      {
        "suite": "buildSeismicMass",
        "name": "conserves total member self-mass (Σ nodal = Σ member)"
      },
      {
        "suite": "modalAnalysis — SDOF cantilever column",
        "name": "fundamental period matches 2π√(m/k) with k from a static unit load"
      },
      {
        "suite": "modalAnalysis — SDOF cantilever column",
        "name": "the lateral modes account for ~100% of the mass in their direction"
      },
      {
        "suite": "modalAnalysis — SDOF cantilever column",
        "name": "mode shape is a record with max |component| = 1 and only the free top node"
      },
      {
        "suite": "modalAnalysis — generated grid",
        "name": "returns positive periods in descending order with growing cumulative mass"
      },
      {
        "suite": "modalAnalysis — generated grid",
        "name": "returns null for a model with no supports (singular K)"
      }
    ]
  },
  {
    "module": "responseSpectrum",
    "group": "Dynamics",
    "title": "SRSS / CQC response spectrum",
    "integration": false,
    "tests": [
      {
        "suite": "nscp208Spectrum",
        "name": "plateau governs at T = 0 (velocity → ∞, capped)"
      },
      {
        "suite": "nscp208Spectrum",
        "name": "plateau governs at T = Ts (velocity branch meets plateau)"
      },
      {
        "suite": "nscp208Spectrum",
        "name": "velocity branch: Sa = Cv·I·g/(R·T) for Ts < T < T_min"
      },
      {
        "suite": "nscp208Spectrum",
        "name": "minimum floor governs at long periods"
      },
      {
        "suite": "nscp208Spectrum",
        "name": "Sa is monotonically non-increasing (or flat)"
      },
      {
        "suite": "cqcCorrel",
        "name": "diagonal is 1 (identical frequencies)"
      },
      {
        "suite": "cqcCorrel",
        "name": "approaches 0 for well-separated modes"
      },
      {
        "suite": "cqcCorrel",
        "name": "is symmetric: ρ(i,j) = ρ(j,i)"
      },
      {
        "suite": "cqcCorrel",
        "name": "lies in [0, 1] for a range of frequency ratios"
      },
      {
        "suite": "computeResponseSpectrum",
        "name": "CQC ≥ SRSS (positive cross-correlations add to SRSS)"
      },
      {
        "suite": "computeResponseSpectrum",
        "name": "all base shears are non-negative"
      },
      {
        "suite": "computeResponseSpectrum",
        "name": "Ts = Cv/(2.5·Ca)"
      },
      {
        "suite": "computeResponseSpectrum",
        "name": "SRSS equals √(Σ V_i²) computed independently"
      },
      {
        "suite": "computeResponseSpectrum",
        "name": "single mode: CQC = SRSS = Sa·effMass"
      },
      {
        "suite": "computeResponseSpectrum",
        "name": "cqcRatio populated only when staticV is non-zero"
      },
      {
        "suite": "computeResponseSpectrum",
        "name": "empty modes → zero base shears"
      },
      {
        "suite": "rsaEquivalentLoads",
        "name": "combined base shear reproduces computeResponseSpectrum (CQC and SRSS, X and Z)"
      },
      {
        "suite": "rsaEquivalentLoads",
        "name": "single mode: base shear = Sa·effMass (hand calc)"
      },
      {
        "suite": "rsaEquivalentLoads",
        "name": "storey forces back-difference the combined shear diagram (ΣF = V_base)"
      },
      {
        "suite": "rsaEquivalentLoads",
        "name": "§208.6.4.2 scaling: forces scale up to the floor, never down"
      },
      {
        "suite": "rsaEquivalentLoads",
        "name": "node loads: cat E, correct component, per-level sums match storey forces"
      },
      {
        "suite": "rsaEquivalentLoads",
        "name": "reports directional mass participation (§208.6.4.1 ≥ 90% check)"
      },
      {
        "suite": "rsaEquivalentLoads",
        "name": "null for empty modes"
      }
    ]
  },
  {
    "module": "accelSpectrum",
    "group": "Dynamics",
    "title": "Elastic response spectra",
    "integration": false,
    "tests": [
      {
        "suite": "elasticResponseSpectrum — pseudo-spectral relationships",
        "name": "returns a spectrum anchored at T = 0 with S_a(0) = PGA"
      },
      {
        "suite": "elasticResponseSpectrum — pseudo-spectral relationships",
        "name": "PSV = ω·Sd and PSA = ω²·Sd hold exactly at every finite period"
      },
      {
        "suite": "elasticResponseSpectrum — pseudo-spectral relationships",
        "name": "points are sorted ascending in period"
      },
      {
        "suite": "elasticResponseSpectrum — resonance amplification",
        "name": "a 2 Hz harmonic peaks near T = 0.5 s, amplified well above PGA"
      },
      {
        "suite": "elasticResponseSpectrum — resonance amplification",
        "name": "higher damping reduces the resonant peak"
      },
      {
        "suite": "elasticResponseSpectrum — guards",
        "name": "empty record or non-positive dt → null"
      },
      {
        "suite": "elasticResponseSpectrum — guards",
        "name": "zero ground motion → flat zero spectrum (PGA = 0)"
      },
      {
        "suite": "nscp208DesignCurve — overlay sampling",
        "name": "matches nscp208Spectrum at each period and exposes Sa/g"
      }
    ]
  },
  {
    "module": "accelerogram",
    "group": "Dynamics",
    "title": "Ground-motion records",
    "integration": false,
    "tests": [
      {
        "suite": "two-column CSV (time, ag)",
        "name": "parses values and derives dt from the time axis"
      },
      {
        "suite": "two-column CSV (time, ag)",
        "name": "scales g → m/s² when units is g"
      },
      {
        "suite": "two-column CSV (time, ag)",
        "name": "leaves values unchanged when units is ms2"
      },
      {
        "suite": "two-column CSV (time, ag)",
        "name": "reports correct PGA"
      },
      {
        "suite": "two-column CSV (time, ag)",
        "name": "skips comment lines and header rows"
      },
      {
        "suite": "one-column CSV (dt from opts)",
        "name": "parses with dt from opts"
      },
      {
        "suite": "one-column CSV (dt from opts)",
        "name": "returns null without a dt source"
      },
      {
        "suite": "one-column CSV (dt from opts)",
        "name": "applies g scaling for one-column"
      },
      {
        "suite": "PEER AT2 multi-value format",
        "name": "picks up DT from the header line"
      },
      {
        "suite": "PEER AT2 multi-value format",
        "name": "collects all values across rows"
      },
      {
        "suite": "PEER AT2 multi-value format",
        "name": "opts.dt overrides DT header when provided"
      },
      {
        "suite": "comment and empty line handling",
        "name": "skips # comments"
      },
      {
        "suite": "comment and empty line handling",
        "name": "skips % comments (MATLAB style)"
      },
      {
        "suite": "comment and empty line handling",
        "name": "skips ! comments"
      },
      {
        "suite": "comment and empty line handling",
        "name": "ignores blank lines"
      },
      {
        "suite": "guards",
        "name": "returns null for empty string"
      },
      {
        "suite": "guards",
        "name": "returns null for all-comment file"
      },
      {
        "suite": "guards",
        "name": "pga is always non-negative"
      }
    ]
  },
  {
    "module": "timeHistory",
    "group": "Dynamics",
    "title": "Newmark SDOF / modal integration",
    "integration": false,
    "tests": [
      {
        "suite": "newmarkSDOF — analytical SDOF responses",
        "name": "undamped free vibration: u(t) = cos(ωt)"
      },
      {
        "suite": "newmarkSDOF — analytical SDOF responses",
        "name": "undamped step load from rest: u(t) = (p0/ω²)(1 − cos ωt), peak = 2p0/ω²"
      },
      {
        "suite": "newmarkSDOF — analytical SDOF responses",
        "name": "damped step load reaches the static deflection p0/ω²"
      },
      {
        "suite": "newmarkSDOF — analytical SDOF responses",
        "name": "damped free vibration decays with the right log-decrement"
      },
      {
        "suite": "newmarkSDOF — analytical SDOF responses",
        "name": "empty record yields empty histories"
      },
      {
        "suite": "modalTimeHistory",
        "name": "returns null for an empty record"
      },
      {
        "suite": "modalTimeHistory",
        "name": "produces consistent dimensions and modal data"
      },
      {
        "suite": "modalTimeHistory",
        "name": "modal coordinate D_r matches a standalone Newmark solve of the SDOF"
      },
      {
        "suite": "modalTimeHistory",
        "name": "base shear equals Σ effMass·ω²·D from the modal results"
      },
      {
        "suite": "modalTimeHistory",
        "name": "peak base shear ≈ effMass · spectral pseudo-acceleration (single dominant mode cross-check)"
      },
      {
        "suite": "modalTimeHistory",
        "name": "peak nodal displacement is the time-max of Σ φ·Γ·D (recombination check)"
      },
      {
        "suite": "modalTimeHistory",
        "name": "zero ground motion → zero response"
      },
      {
        "suite": "modalTimeHistory",
        "name": "stronger excitation scales the response linearly"
      },
      {
        "suite": "modalTimeHistory",
        "name": "historyNode returns the full node displacement history; its max = peakDisp"
      }
    ]
  },
  {
    "module": "timeHistoryModel",
    "group": "Dynamics",
    "title": "Model-level modal time history",
    "integration": false,
    "tests": [
      {
        "suite": "makeGroundMotion",
        "name": "harmonic: a_g = PGA·sin(2πf t), correct length and peak"
      },
      {
        "suite": "makeGroundMotion",
        "name": "pulse: zero after one period"
      },
      {
        "suite": "makeGroundMotion",
        "name": "rampedSine: starts near zero and decays toward the end"
      },
      {
        "suite": "runTimeHistoryModel",
        "name": "runs and returns base-shear + roof histories at the roof control node"
      },
      {
        "suite": "runTimeHistoryModel",
        "name": "csv: accepts a two-column accelerogram and returns source=csv"
      },
      {
        "suite": "runTimeHistoryModel",
        "name": "csv: returns null when CSV cannot be parsed (one-column without dt)"
      },
      {
        "suite": "runTimeHistoryModel",
        "name": "returns null without spec or csv"
      },
      {
        "suite": "runTimeHistoryModel",
        "name": "returns null for an empty model"
      }
    ]
  },
  {
    "module": "directTimeHistory",
    "group": "Dynamics",
    "title": "Direct MDOF Newmark, Rayleigh damping",
    "integration": false,
    "tests": [
      {
        "suite": "directTimeHistory — Rayleigh damping model",
        "name": "reproduces the two target damping ratios exactly"
      },
      {
        "suite": "directTimeHistory — Rayleigh damping model",
        "name": "supports unequal anchor ratios"
      },
      {
        "suite": "directTimeHistory — Rayleigh damping model",
        "name": "dips below the target between the anchors and rises outside them"
      },
      {
        "suite": "directTimeHistory — Rayleigh damping model",
        "name": "α alone gives mass-proportional damping ζ = α/2ω"
      },
      {
        "suite": "directTimeHistory — newmarkDirect on a 1-DOF system",
        "name": "matches newmarkSDOF step for step"
      },
      {
        "suite": "directTimeHistory — newmarkDirect on a 1-DOF system",
        "name": "free vibration decays at the logarithmic decrement of ζ"
      },
      {
        "suite": "directTimeHistory — newmarkDirect on a 1-DOF system",
        "name": "returns null when the effective stiffness is singular"
      },
      {
        "suite": "directTimeHistory — direct integration ≡ modal superposition (2-DOF)",
        "name": "the eigen-solution matches the golden-ratio closed form"
      },
      {
        "suite": "directTimeHistory — direct integration ≡ modal superposition (2-DOF)",
        "name": "Rayleigh gives exactly ζ in BOTH modes (so the two paths are comparable)"
      },
      {
        "suite": "directTimeHistory — direct integration ≡ modal superposition (2-DOF)",
        "name": "agrees with mode-by-mode superposition to roundoff"
      },
      {
        "suite": "directTimeHistory — model level",
        "name": "runs the full free-DOF system and reports the Rayleigh anchors"
      },
      {
        "suite": "directTimeHistory — model level",
        "name": "produces finite peaks and a non-trivial base-shear history"
      },
      {
        "suite": "directTimeHistory — model level",
        "name": "lands in the same ballpark as modal superposition"
      },
      {
        "suite": "directTimeHistory — model level",
        "name": "returns the requested node displacement history"
      },
      {
        "suite": "directTimeHistory — model level",
        "name": "heavier damping reduces the peak response"
      },
      {
        "suite": "directTimeHistory — model level",
        "name": "returns null for an empty record"
      }
    ]
  },
  {
    "module": "buckling",
    "group": "Dynamics",
    "title": "Linearized buckling",
    "integration": false,
    "tests": [
      {
        "suite": "bucklingFromFrame — cantilever column (H = 3 m, P = 1 kN)",
        "name": "returns at least one mode for a compressive cantilever"
      },
      {
        "suite": "bucklingFromFrame — cantilever column (H = 3 m, P = 1 kN)",
        "name": "λ within 1.5 % of π²EI/(4H²)/P (1-element FEM is slightly stiff)"
      },
      {
        "suite": "bucklingFromFrame — cantilever column (H = 3 m, P = 1 kN)",
        "name": "critical load factor λ > 0 (compressive loading)"
      },
      {
        "suite": "bucklingFromFrame — cantilever column (H = 3 m, P = 1 kN)",
        "name": "max-normalised buckling shape has max |component| = 1"
      },
      {
        "suite": "bucklingFromFrame — cantilever column (H = 3 m, P = 1 kN)",
        "name": "tip node has dominant lateral displacement in the mode shape"
      },
      {
        "suite": "bucklingFromFrame — fixed–fixed column 2 elements (H = 4 m, P = 1 kN)",
        "name": "λ within 2 % of 4π²EI/H²/P (2-element FEM)"
      },
      {
        "suite": "bucklingFromFrame — fixed–fixed column 2 elements (H = 4 m, P = 1 kN)",
        "name": "buckling shape: mid-node has peak lateral displacement; fixed ends have zero"
      },
      {
        "suite": "bucklingFromFrame — sign and edge cases",
        "name": "tension member (N > 0) → null (no positive buckling mode)"
      },
      {
        "suite": "bucklingFromFrame — sign and edge cases",
        "name": "zero axial force → null (no geometric stiffness)"
      },
      {
        "suite": "bucklingFromFrame — sign and edge cases",
        "name": "cantilever: λ scales as 1/H² (Pcr ∝ 1/H²)"
      }
    ]
  },
  {
    "module": "hysteresis",
    "group": "Nonlinear",
    "title": "Bilinear kinematic hysteresis",
    "integration": false,
    "tests": [
      {
        "suite": "hysteresis — bilinear kinematic hardening",
        "name": "is linear below yield and caps at Fy (elastic-perfectly-plastic)"
      },
      {
        "suite": "hysteresis — bilinear kinematic hardening",
        "name": "hardens on the post-yield branch at b·k₀"
      },
      {
        "suite": "hysteresis — bilinear kinematic hardening",
        "name": "unloads elastically at k₀ after yielding (the thing pushover cannot do)"
      },
      {
        "suite": "hysteresis — bilinear kinematic hardening",
        "name": "yields in the reverse direction after a full reversal"
      },
      {
        "suite": "hysteresis — bilinear kinematic hardening",
        "name": "dissipates the closed-form loop energy 4·Fy·(A − u_y) per steady-state cycle"
      },
      {
        "suite": "hysteresis — bilinear kinematic hardening",
        "name": "dissipates nothing while the response stays elastic"
      },
      {
        "suite": "hysteresis — bilinear kinematic hardening",
        "name": "an infinite Fy is a plain linear spring"
      }
    ]
  },
  {
    "module": "smoothHinge",
    "group": "Nonlinear",
    "title": "Smooth (C^∞) hinge backbone",
    "integration": false,
    "tests": [
      {
        "suite": "smoothHinge — the two asymptotes it joins",
        "name": "is elastic at the origin: slope k0, force 0"
      },
      {
        "suite": "smoothHinge — the two asymptotes it joins",
        "name": "approaches the post-yield line b·k0·u + (1−b)·Fy far past the knee"
      },
      {
        "suite": "smoothHinge — the two asymptotes it joins",
        "name": "agrees with the bilinear backbone away from the knee, both directions"
      },
      {
        "suite": "smoothHinge — the two asymptotes it joins",
        "name": "matches `bilinearProbe` on its virgin backbone away from the knee"
      },
      {
        "suite": "smoothHinge — the two asymptotes it joins",
        "name": "rounds the corner — inside the knee it is BELOW the bilinear force"
      },
      {
        "suite": "smoothHinge — smoothness, which is the whole point",
        "name": "the reported tangent IS df/du, including right through the knee"
      },
      {
        "suite": "smoothHinge — smoothness, which is the whole point",
        "name": "the tangent is continuous across the knee — no jump to fall through"
      },
      {
        "suite": "smoothHinge — smoothness, which is the whole point",
        "name": "the tangent stays between the two asymptote slopes"
      },
      {
        "suite": "smoothHinge — smoothness, which is the whole point",
        "name": "a SOFTENING hinge has a genuinely negative tangent past the knee"
      },
      {
        "suite": "smoothHinge — it is nonlinear ELASTIC, and says so",
        "name": "is an odd function: unloading retraces loading"
      },
      {
        "suite": "smoothHinge — it is nonlinear ELASTIC, and says so",
        "name": "a full cycle returns to the origin with zero net work — no dissipation"
      },
      {
        "suite": "smoothHinge — it is nonlinear ELASTIC, and says so",
        "name": "leaves NO permanent set, unlike the plastic law it smooths"
      },
      {
        "suite": "smoothHinge — degenerate inputs",
        "name": "an infinite capacity is purely linear"
      },
      {
        "suite": "smoothHinge — degenerate inputs",
        "name": "a zero capacity degenerates to the post-yield line alone"
      },
      {
        "suite": "smoothHinge — degenerate inputs",
        "name": "b defaults to perfectly plastic"
      },
      {
        "suite": "smoothHinge — degenerate inputs",
        "name": "the yield deformation is Fy/k0"
      }
    ]
  },
  {
    "module": "biaxialHinge",
    "group": "Nonlinear",
    "title": "Biaxial (P–My–Mz) hinge constitutive law",
    "integration": false,
    "tests": [
      {
        "suite": "biaxialHinge — elastic range",
        "name": "is uncoupled and linear below the surface"
      },
      {
        "suite": "biaxialHinge — elastic range",
        "name": "never yields when neither axis has capacity"
      },
      {
        "suite": "biaxialHinge — degenerates to the 1-D bilinear hinge",
        "name": "matches bilinearPath exactly when the other axis has no capacity"
      },
      {
        "suite": "biaxialHinge — degenerates to the 1-D bilinear hinge",
        "name": "matches bilinearPath exactly when the other axis is simply unloaded"
      },
      {
        "suite": "biaxialHinge — degenerates to the 1-D bilinear hinge",
        "name": "unloads elastically — the tangent snaps back to k₀"
      },
      {
        "suite": "biaxialHinge — the coupled surface is the whole point",
        "name": "yields at 0.8Mpy + 0.8Mpz, which two 1-D hinges would call elastic"
      },
      {
        "suite": "biaxialHinge — the coupled surface is the whole point",
        "name": "projects a 45° push onto the circle when the capacities are equal"
      },
      {
        "suite": "biaxialHinge — the coupled surface is the whole point",
        "name": "lands on the ellipse for unequal capacities"
      },
      {
        "suite": "biaxialHinge — the coupled surface is the whole point",
        "name": "flows normal to the surface (associativity)"
      },
      {
        "suite": "biaxialHinge — consistent tangent",
        "name": "matches finite differences on the elliptical surface"
      },
      {
        "suite": "biaxialHinge — consistent tangent",
        "name": "matches finite differences on the Bresler contour (α = 1.5)"
      },
      {
        "suite": "biaxialHinge — consistent tangent",
        "name": "matches finite differences on the Orbison surface under axial load"
      },
      {
        "suite": "biaxialHinge — consistent tangent",
        "name": "softens the unloaded axis at a uniaxial yielded state"
      },
      {
        "suite": "biaxialHinge — Orbison surface (McGuire/Ziemian Eq. 10.18)",
        "name": "reaches the full plastic moment on each axis at zero axial load"
      },
      {
        "suite": "biaxialHinge — Orbison surface (McGuire/Ziemian Eq. 10.18)",
        "name": "matches the closed-form contour at p = 0.3"
      },
      {
        "suite": "biaxialHinge — Orbison surface (McGuire/Ziemian Eq. 10.18)",
        "name": "squashes at p = 1/√1.15 = 0.933 — Orbison’s fit, slightly conservative"
      },
      {
        "suite": "biaxialHinge — Orbison surface (McGuire/Ziemian Eq. 10.18)",
        "name": "shrinks the moment capacity monotonically with axial load"
      },
      {
        "suite": "biaxialHinge — Orbison surface (McGuire/Ziemian Eq. 10.18)",
        "name": "is sign-agnostic in axial force (even powers only)"
      },
      {
        "suite": "biaxialHinge — power (Bresler) surface",
        "name": "reproduces the Bresler contour at α = 1.5"
      },
      {
        "suite": "biaxialHinge — power (Bresler) surface",
        "name": "is more permissive as α grows — α = 1 is the conservative linear chord"
      },
      {
        "suite": "biaxialHinge — power (Bresler) surface",
        "name": "keeps the |m|^α regularisation far below any working tolerance"
      },
      {
        "suite": "biaxialHinge — power (Bresler) surface",
        "name": "handles a hinge whose capacity has been reduced to zero by axial load"
      },
      {
        "suite": "biaxialHinge — capacities, utilisation and dissipation",
        "name": "reduces both axes through the codified uniaxial P–M chords"
      },
      {
        "suite": "biaxialHinge — capacities, utilisation and dissipation",
        "name": "reports utilisation as demand/capacity, like every other check in the repo"
      },
      {
        "suite": "biaxialHinge — capacities, utilisation and dissipation",
        "name": "agrees with the yield function on which side of the surface a point is"
      },
      {
        "suite": "biaxialHinge — capacities, utilisation and dissipation",
        "name": "dissipates only through plastic flow, and never negatively"
      },
      {
        "suite": "biaxialHinge — capacities, utilisation and dissipation",
        "name": "matches the 1-D dissipated energy on a uniaxial cycle"
      },
      {
        "suite": "biaxialHinge — capacities, utilisation and dissipation",
        "name": "converges the return map everywhere on a dense skew sweep"
      }
    ]
  },
  {
    "module": "pushover",
    "group": "Nonlinear",
    "title": "Event-to-event pushover",
    "integration": false,
    "tests": [
      {
        "suite": "pushover — horizontal cantilever (single Mz hinge at base)",
        "name": "first hinge forms at the base, then mechanism (pinned base → unstable)"
      },
      {
        "suite": "pushover — horizontal cantilever (single Mz hinge at base)",
        "name": "capacity base shear = Mp / L and roof disp = Mp·L²/(3EIz)"
      },
      {
        "suite": "pushover — fixed–fixed beam, central load (limit load 8·Mp/L)",
        "name": "collapses at P_u ≈ 8·Mp/L with a mechanism"
      },
      {
        "suite": "pushover — fixed–fixed beam, central load (limit load 8·Mp/L)",
        "name": "first yield matches the elastic peak-moment demand (Mp / max elastic M per unit load)"
      },
      {
        "suite": "pushover — fixed-base portal frame",
        "name": "forms a column-sway mechanism with four My hinges"
      },
      {
        "suite": "pushover — fixed-base portal frame",
        "name": "first yield = Mp / (max elastic column moment per unit load)"
      },
      {
        "suite": "pushover — fixed-base portal frame",
        "name": "capacity curve: displacement increases and secant stiffness never increases"
      },
      {
        "suite": "pushover — fixed-base portal frame",
        "name": "respects targetDisp early stop"
      },
      {
        "suite": "pushover — P-Δ second order (gravity softens the capacity curve)",
        "name": "first-order capacity = Mp / L with no gravity"
      },
      {
        "suite": "pushover — P-Δ second order (gravity softens the capacity curve)",
        "name": "base moment = lateral V·L plus the P·Δ second-order term (≈ Mp at yield)"
      },
      {
        "suite": "pushover — P-Δ second order (gravity softens the capacity curve)",
        "name": "P-Δ lowers the collapse base shear and amplifies roof drift"
      },
      {
        "suite": "pushover — P-Δ second order (gravity softens the capacity curve)",
        "name": "heavier gravity ⇒ lower collapse base shear (monotone softening)"
      },
      {
        "suite": "pushover — P-Δ second order (gravity softens the capacity curve)",
        "name": "pDelta on but no gravity ⇒ identical to first order"
      },
      {
        "suite": "pushover — P-Δ second order (gravity softens the capacity curve)",
        "name": "gravity given but pDelta off ⇒ gravity ignored (first order)"
      },
      {
        "suite": "pushover — guards",
        "name": "zero load pattern returns only the origin"
      },
      {
        "suite": "pushover — guards",
        "name": "no Mp assigned → stays elastic (origin only, not a mechanism)"
      },
      {
        "suite": "pushover — axial hinge (brace yielding caps base shear at Pp)",
        "name": "forms one axial hinge then a mechanism"
      },
      {
        "suite": "pushover — axial hinge (brace yielding caps base shear at Pp)",
        "name": "capacity base shear equals the axial capacity Pp"
      },
      {
        "suite": "pushover — shear hinge competes with flexure",
        "name": "shear-controlled: small Vp, large Mp ⇒ a shear hinge at base shear = Vp"
      },
      {
        "suite": "pushover — shear hinge competes with flexure",
        "name": "flexure-controlled: large Vp, small Mp ⇒ a moment hinge at base shear = Mp/L"
      },
      {
        "suite": "pushover — shear hinge competes with flexure",
        "name": "per-axis Vp { y, z } is accepted and the loaded axis governs"
      },
      {
        "suite": "pushover — P–M interaction reduces hinge capacity",
        "name": "the peak base shear with P–M ≤ without P–M"
      },
      {
        "suite": "pushover — P–M interaction reduces hinge capacity",
        "name": "hinge records carry the axial force and reduced Mpc (≤ Mp)"
      },
      {
        "suite": "pushover — P–M interaction reduces hinge capacity",
        "name": "without pm the hinge records omit axial/Mpc (backward compatible)"
      }
    ]
  },
  {
    "module": "pushoverModel",
    "group": "Nonlinear",
    "title": "Model-level pushover",
    "integration": false,
    "tests": [
      {
        "suite": "plasticMoment",
        "name": "concrete: ρ·b·d²·fy·(1−0.59ρfy/fc)"
      },
      {
        "suite": "plasticMoment",
        "name": "steel W: Mp = Fy·Zx"
      },
      {
        "suite": "plasticMoment",
        "name": "scales with the concrete ratio ρ (monotone increasing under-reinforced)"
      },
      {
        "suite": "runPushoverModel",
        "name": "runs and returns a capacity curve with a roof control node"
      },
      {
        "suite": "runPushoverModel",
        "name": "curve is monotonic in displacement (event-to-event)"
      },
      {
        "suite": "runPushoverModel",
        "name": "mpScale lifts the capacity proportionally at first yield"
      },
      {
        "suite": "runPushoverModel",
        "name": "returns null for an empty model"
      },
      {
        "suite": "runPushoverModel",
        "name": "pmInteraction defaults off; flag is reported in the result"
      },
      {
        "suite": "runPushoverModel",
        "name": "P–M interaction lowers (or matches) the peak base shear"
      },
      {
        "suite": "runPushoverModel",
        "name": "pDelta defaults off; flag is reported in the result"
      },
      {
        "suite": "runPushoverModel",
        "name": "P-Δ lowers (or matches) the first-yield base shear from gravity softening"
      },
      {
        "suite": "axialCapacity",
        "name": "concrete: Pn0 = 0.85·f′c·Ag"
      },
      {
        "suite": "axialCapacity",
        "name": "steel: Py = Fy·A from the AISC shape"
      }
    ]
  },
  {
    "module": "nonlinearFrame",
    "group": "Nonlinear",
    "title": "Member-end plastic hinges (static)",
    "integration": false,
    "tests": [
      {
        "suite": "nonlinearFrame — elastic behaviour",
        "name": "reproduces the cantilever closed form δ = PL³/3EI exactly (no hinges)"
      },
      {
        "suite": "nonlinearFrame — elastic behaviour",
        "name": "a rigid unyielded hinge does not soften the elastic frame"
      },
      {
        "suite": "nonlinearFrame — elastic behaviour",
        "name": "a linear (elastic) system converges in one Newton iteration"
      },
      {
        "suite": "nonlinearFrame — plastic collapse vs limit analysis",
        "name": "cantilever collapses at P = Mp/L"
      },
      {
        "suite": "nonlinearFrame — plastic collapse vs limit analysis",
        "name": "fixed–fixed beam under a central load collapses at P = 8·Mp/L"
      },
      {
        "suite": "nonlinearFrame — plastic collapse vs limit analysis",
        "name": "more hardening carries more load past first yield"
      },
      {
        "suite": "nonlinearFrame — cyclic response (hinges unload and re-yield)",
        "name": "leaves a permanent set after unloading to zero load"
      },
      {
        "suite": "nonlinearFrame — cyclic response (hinges unload and re-yield)",
        "name": "dissipates energy and records plastic rotation at the hinge"
      },
      {
        "suite": "nonlinearFrame — cyclic response (hinges unload and re-yield)",
        "name": "yields in BOTH directions over a full cycle"
      },
      {
        "suite": "nonlinearFrame — cyclic response (hinges unload and re-yield)",
        "name": "an elastic cycle dissipates nothing and returns to the origin"
      },
      {
        "suite": "nonlinearFrame — guards",
        "name": "returns null for an empty model"
      },
      {
        "suite": "nonlinearFrame — guards",
        "name": "returns null when a member references a missing node"
      },
      {
        "suite": "nonlinearFrame — P–M interaction reduces the hinge capacity",
        "name": "yields EARLIER with P–M than without — the unconservative case it fixes"
      },
      {
        "suite": "nonlinearFrame — P–M interaction reduces the hinge capacity",
        "name": "is inert when Pcap is not supplied — capacity stays at the pure-bending Mp"
      },
      {
        "suite": "nonlinearFrame — P–M interaction reduces the hinge capacity",
        "name": "reduces the COLUMN capacities below Mp while the beam keeps its own"
      },
      {
        "suite": "nonlinearFrame — P–M interaction reduces the hinge capacity",
        "name": "recovers opposite axial forces in the two columns"
      },
      {
        "suite": "nonlinearFrame — P–M interaction reduces the hinge capacity",
        "name": "a smaller axial capacity means a bigger reduction and earlier yield"
      },
      {
        "suite": "nonlinearFrame — displacement control",
        "name": "hits the prescribed control displacement at every step"
      },
      {
        "suite": "nonlinearFrame — displacement control",
        "name": "agrees with the elastic closed form while the response is elastic"
      },
      {
        "suite": "nonlinearFrame — displacement control",
        "name": "HOLDS the collapse load flat instead of running away (load control cannot)"
      },
      {
        "suite": "nonlinearFrame — displacement control",
        "name": "traces a DESCENDING post-peak branch when the hinge softens"
      },
      {
        "suite": "nonlinearFrame — displacement control",
        "name": "reports the solved load factor as an output"
      },
      {
        "suite": "nonlinearFrame — multi-hinge convergence",
        "name": "converges at every step of a 56-hinge frame"
      },
      {
        "suite": "nonlinearFrame — multi-hinge convergence",
        "name": "reports a capacity that does not depend on the step count"
      },
      {
        "suite": "nonlinearFrame — multi-hinge convergence",
        "name": "reports the residual it actually achieved"
      }
    ]
  },
  {
    "module": "nonlinearFrameDynamic",
    "group": "Nonlinear",
    "title": "Member-end plastic hinges (dynamic)",
    "integration": false,
    "tests": [
      {
        "suite": "nonlinearFrameDynamic — elastic limit ≡ linear Newmark",
        "name": "matches newmarkDirect on the same K, M, C when nothing yields"
      },
      {
        "suite": "nonlinearFrameDynamic — elastic limit ≡ linear Newmark",
        "name": "an elastic run converges in one Newton iteration"
      },
      {
        "suite": "nonlinearFrameDynamic — inelastic response",
        "name": "adds a hinge DOF per hinged member end"
      },
      {
        "suite": "nonlinearFrameDynamic — inelastic response",
        "name": "stays elastic under a weak record"
      },
      {
        "suite": "nonlinearFrameDynamic — inelastic response",
        "name": "yields, dissipates energy and reports which hinges formed"
      },
      {
        "suite": "nonlinearFrameDynamic — inelastic response",
        "name": "yielding cuts the base shear below the elastic demand"
      },
      {
        "suite": "nonlinearFrameDynamic — inelastic response",
        "name": "a weaker frame shows more hinging and larger plastic rotation demand"
      },
      {
        "suite": "nonlinearFrameDynamic — inelastic response",
        "name": "returns null for an empty record or a massless frame"
      }
    ]
  },
  {
    "module": "nonlinearFrameModel",
    "group": "Nonlinear",
    "title": "Equivalent plane-frame bridge",
    "integration": false,
    "tests": [
      {
        "suite": "nonlinearFrameModel — condensing 3D to an equivalent plane frame",
        "name": "collapses the perpendicular coordinate onto one frame line"
      },
      {
        "suite": "nonlinearFrameModel — condensing 3D to an equivalent plane frame",
        "name": "drops transverse members and keeps the in-plane ones"
      },
      {
        "suite": "nonlinearFrameModel — condensing 3D to an equivalent plane frame",
        "name": "preserves the total seismic mass"
      },
      {
        "suite": "nonlinearFrameModel — condensing 3D to an equivalent plane frame",
        "name": "sums stiffness and capacity across the combined parallel frames"
      },
      {
        "suite": "nonlinearFrameModel — condensing 3D to an equivalent plane frame",
        "name": "marks the roof node as the control node and keeps the supports"
      },
      {
        "suite": "nonlinearFrameModel — condensing 3D to an equivalent plane frame",
        "name": "returns null when nothing lies in the loading plane"
      },
      {
        "suite": "nonlinearFrameModel — equivalent period vs the full 3D modal T₁",
        "name": "lands within 10% for 1-, 2- and 3-storey frames"
      },
      {
        "suite": "nonlinearFrameModel — equivalent period vs the full 3D modal T₁",
        "name": "period grows with height"
      },
      {
        "suite": "nonlinearFrameModel — analyses on the condensed frame",
        "name": "runs a nonlinear time history and reports the frame + period"
      },
      {
        "suite": "nonlinearFrameModel — analyses on the condensed frame",
        "name": "an elastic reference run never yields"
      },
      {
        "suite": "nonlinearFrameModel — analyses on the condensed frame",
        "name": "a strong record hinges the frame and cuts base shear below elastic"
      },
      {
        "suite": "nonlinearFrameModel — analyses on the condensed frame",
        "name": "the same condensed frame also pushes over statically"
      },
      {
        "suite": "nonlinearFrameModel — analyses on the condensed frame",
        "name": "returns null for an empty record"
      },
      {
        "suite": "nonlinearFrameModel — P–M interaction through the bridge",
        "name": "supplies Pcap and a material-appropriate P–M surface by default"
      },
      {
        "suite": "nonlinearFrameModel — P–M interaction through the bridge",
        "name": "sums axial capacity across the combined parallel frames, like stiffness"
      },
      {
        "suite": "nonlinearFrameModel — P–M interaction through the bridge",
        "name": "can be switched off, and is off for the elastic reference frame"
      }
    ]
  },
  {
    "module": "nonlinearModel",
    "group": "Nonlinear",
    "title": "Shear-building reduction",
    "integration": false,
    "tests": [
      {
        "suite": "nonlinearModel — storey reduction",
        "name": "produces one storey entry per framed level, bottom-up"
      },
      {
        "suite": "nonlinearModel — storey reduction",
        "name": "gives every storey a positive mass, stiffness and capacity"
      },
      {
        "suite": "nonlinearModel — storey reduction",
        "name": "storey stiffness decreases with height (upper storeys are less restrained)"
      },
      {
        "suite": "nonlinearModel — storey reduction",
        "name": "capacity follows the shear-type mechanism Σ 2·Mp/h"
      },
      {
        "suite": "nonlinearModel — storey reduction",
        "name": "returns null for a model with no framed levels"
      },
      {
        "suite": "nonlinearModel — reduced period vs the full 3D modal period",
        "name": "lands within 10% of modal T₁ for 1-, 2- and 3-storey frames"
      },
      {
        "suite": "nonlinearModel — reduced period vs the full 3D modal period",
        "name": "period grows with the number of storeys"
      },
      {
        "suite": "nonlinearModel — response history",
        "name": "carries the reduction, the period and a converged response"
      },
      {
        "suite": "nonlinearModel — response history",
        "name": "the elastic reference run never yields or dissipates"
      },
      {
        "suite": "nonlinearModel — response history",
        "name": "a strong record yields the frame and dissipates energy"
      },
      {
        "suite": "nonlinearModel — response history",
        "name": "yielding caps the base force below the elastic demand"
      },
      {
        "suite": "nonlinearModel — response history",
        "name": "a weak record keeps the frame elastic"
      },
      {
        "suite": "nonlinearModel — response history",
        "name": "returns null for an empty record"
      }
    ]
  },
  {
    "module": "nonlinearTimeHistory",
    "group": "Nonlinear",
    "title": "Newmark + Newton-Raphson",
    "integration": false,
    "tests": [
      {
        "suite": "nonlinearTimeHistory — K₀ assembly",
        "name": "builds the classic shear-building stiffness from grounded + chained springs"
      },
      {
        "suite": "nonlinearTimeHistory — reduces to newmarkDirect when nothing yields",
        "name": "matches the linear solver step for step"
      },
      {
        "suite": "nonlinearTimeHistory — reduces to newmarkDirect when nothing yields",
        "name": "a linear system converges in a single Newton iteration"
      },
      {
        "suite": "nonlinearTimeHistory — inelastic response",
        "name": "stays elastic and dissipates nothing with a high yield force"
      },
      {
        "suite": "nonlinearTimeHistory — inelastic response",
        "name": "yields, dissipates energy and caps the base force at Fy"
      },
      {
        "suite": "nonlinearTimeHistory — inelastic response",
        "name": "ductility demand falls monotonically as the yield strength rises"
      },
      {
        "suite": "nonlinearTimeHistory — inelastic response",
        "name": "yielding limits the force below the elastic demand"
      },
      {
        "suite": "nonlinearTimeHistory — inelastic response",
        "name": "post-yield hardening carries more force than a perfectly-plastic system"
      },
      {
        "suite": "nonlinearTimeHistory — inelastic response",
        "name": "reports convergence diagnostics and rejects a degenerate system"
      }
    ]
  },
  {
    "module": "arcLength",
    "group": "Nonlinear",
    "title": "Arc-length (Riks/Crisfield) continuation",
    "integration": false,
    "tests": [
      {
        "suite": "arcLength — elastic path",
        "name": "traces the exact linear path λ = |δ|·3EI/L³"
      },
      {
        "suite": "arcLength — elastic path",
        "name": "the step really is an ARC of the prescribed length"
      },
      {
        "suite": "arcLength — elastic path",
        "name": "halving the arc length doubles the number of steps to the same place"
      },
      {
        "suite": "arcLength — plastic collapse",
        "name": "peak λ is the rigid-plastic collapse load Mp/L"
      },
      {
        "suite": "arcLength — plastic collapse",
        "name": "holds the collapse load flat well past the peak"
      },
      {
        "suite": "arcLength — plastic collapse",
        "name": "a softening hinge (b < 0) produces a genuinely DESCENDING branch"
      },
      {
        "suite": "arcLength — agreement with displacement control where both apply",
        "name": "both reach the same collapse plateau"
      },
      {
        "suite": "arcLength — agreement with displacement control where both apply",
        "name": "the two curves coincide point-by-point"
      },
      {
        "suite": "arcLength — agreement with displacement control where both apply",
        "name": "arc-length keeps a bounded step where displacement control does not"
      },
      {
        "suite": "arcLength — smooth material: ROBUST snap-back",
        "name": "traces a sustained snap-back for |b| > 3 — hundreds of reversals, no failure"
      },
      {
        "suite": "arcLength — smooth material: ROBUST snap-back",
        "name": "the traced path is INDEPENDENT of the arc length — the robustness claim"
      },
      {
        "suite": "arcLength — smooth material: ROBUST snap-back",
        "name": "mild softening still gives a monotone descending branch, no false snap-back"
      },
      {
        "suite": "arcLength — smooth material: ROBUST snap-back",
        "name": "a PERFECTLY PLASTIC hinge still reaches the exact collapse load"
      },
      {
        "suite": "arcLength — smooth material: ROBUST snap-back",
        "name": "with SOFTENING the peak sits at the knee, so smoothing shaves it slightly"
      },
      {
        "suite": "arcLength — smooth material: ROBUST snap-back",
        "name": "is nonlinear elastic: no dissipation and no permanent set"
      },
      {
        "suite": "arcLength — smooth material: ROBUST snap-back",
        "name": "agrees with the bilinear path before anything yields"
      },
      {
        "suite": "arcLength — snap-back on the BILINEAR material (limited, see scope note)",
        "name": "mild softening (|b| < 3) stays monotone in displacement — no snap-back"
      },
      {
        "suite": "arcLength — snap-back on the BILINEAR material (limited, see scope note)",
        "name": "steep softening past the |b| > 3 threshold can be traced onto a REAL snap-back"
      },
      {
        "suite": "arcLength — snap-back on the BILINEAR material (limited, see scope note)",
        "name": "the snapBack flag never fires on a monotone path"
      },
      {
        "suite": "arcLength — robustness",
        "name": "cuts the arc rather than accepting a failed step"
      },
      {
        "suite": "arcLength — robustness",
        "name": "stops cleanly at dispStop instead of running away"
      },
      {
        "suite": "arcLength — robustness",
        "name": "returns null for an unusable control node"
      },
      {
        "suite": "arcLength — robustness",
        "name": "a fixed node cannot be the control DOF (no free DOF to follow)"
      },
      {
        "suite": "arcLength — robustness",
        "name": "energy dissipation is monotone along the path"
      }
    ]
  },
  {
    "module": "nonlinearFrame3d",
    "group": "Nonlinear",
    "title": "Space frame with biaxial hinges",
    "integration": false,
    "tests": [
      {
        "suite": "nonlinearFrame3d — elastic behaviour is the linear solver",
        "name": "reproduces solveFrame3D to machine precision when no member is hinged"
      },
      {
        "suite": "nonlinearFrame3d — elastic behaviour is the linear solver",
        "name": "matches the elastic cantilever formulas on both bending axes"
      },
      {
        "suite": "nonlinearFrame3d — elastic behaviour is the linear solver",
        "name": "an unyielded hinge softens the frame only by the penalty stiffness"
      },
      {
        "suite": "nonlinearFrame3d — elastic behaviour is the linear solver",
        "name": "adds exactly two DOFs per hinged member end, and none for an unhinged member"
      },
      {
        "suite": "nonlinearFrame3d — uniaxial collapse reproduces the plane frame",
        "name": "gives λpeak = Mpz/L for a strong-axis cantilever mechanism"
      },
      {
        "suite": "nonlinearFrame3d — uniaxial collapse reproduces the plane frame",
        "name": "gives λpeak = Mpy/L for a weak-axis cantilever mechanism"
      },
      {
        "suite": "nonlinearFrame3d — uniaxial collapse reproduces the plane frame",
        "name": "agrees with the 2-D engine on the same strong-axis problem"
      },
      {
        "suite": "nonlinearFrame3d — uniaxial collapse reproduces the plane frame",
        "name": "keeps torsion continuous across a hinge"
      },
      {
        "suite": "nonlinearFrame3d — biaxial coupling",
        "name": "is independent of the load angle on a circular surface"
      },
      {
        "suite": "nonlinearFrame3d — biaxial coupling",
        "name": "matches the closed-form ellipse at every skew angle"
      },
      {
        "suite": "nonlinearFrame3d — biaxial coupling",
        "name": "costs capacity relative to treating the axes independently"
      },
      {
        "suite": "nonlinearFrame3d — orientation independence",
        "name": "gives the same collapse load after an arbitrary rigid rotation of the model"
      },
      {
        "suite": "nonlinearFrame3d — orientation independence",
        "name": "matches the closed-form ellipse for a skewed member, in its own local axes"
      },
      {
        "suite": "nonlinearFrame3d — P–M interaction and hinge reporting",
        "name": "reduces the collapse load as axial compression grows"
      },
      {
        "suite": "nonlinearFrame3d — P–M interaction and hinge reporting",
        "name": "reports per-hinge moments, rotations, utilisation and axial force"
      },
      {
        "suite": "nonlinearFrame3d — P–M interaction and hinge reporting",
        "name": "unloads elastically and re-yields under a reversed push"
      }
    ]
  },
  {
    "module": "biaxialFrameModel",
    "group": "Nonlinear",
    "title": "Model → biaxial frame + skew pushover",
    "integration": false,
    "tests": [
      {
        "suite": "weakPlasticMoment",
        "name": "equals the strong-axis capacity for a square section"
      },
      {
        "suite": "weakPlasticMoment",
        "name": "is the strong-axis formula on the section with b and h swapped"
      },
      {
        "suite": "weakPlasticMoment",
        "name": "uses Fy·Zy for a steel W-shape"
      },
      {
        "suite": "modelToBiaxialFrame — bridge",
        "name": "maps members 1:1 and inherits geometry from modelToFrame3D"
      },
      {
        "suite": "modelToBiaxialFrame — bridge",
        "name": "gives every member both plastic capacities and an axial capacity"
      },
      {
        "suite": "modelToBiaxialFrame — bridge",
        "name": "leaves every member elastic under `elastic`"
      },
      {
        "suite": "modelToBiaxialFrame — bridge",
        "name": "reports — never silently drops — releases and offsets it cannot represent"
      },
      {
        "suite": "runBiaxialPushover — skew push on the real 3-D model",
        "name": "normalises the pattern so the load factor IS the base shear"
      },
      {
        "suite": "runBiaxialPushover — skew push on the real 3-D model",
        "name": "converges at every step of the push"
      },
      {
        "suite": "runBiaxialPushover — skew push on the real 3-D model",
        "name": "respects plan symmetry — 0°, 90° and 180° give the same capacity"
      },
      {
        "suite": "runBiaxialPushover — skew push on the real 3-D model",
        "name": "yields hinges and reports a monotone-rising capacity curve"
      },
      {
        "suite": "runBiaxialPushover — skew push on the real 3-D model",
        "name": "stays elastic and linear when hinges are switched off"
      },
      {
        "suite": "runBiaxialPushover — skew push on the real 3-D model",
        "name": "the diagonal push engages both frame lines, so it is not simply weaker"
      },
      {
        "suite": "runBiaxialPushover — skew push on the real 3-D model",
        "name": "the biaxial COUPLING is what limits the diagonal capacity"
      },
      {
        "suite": "runBiaxialPushover — skew push on the real 3-D model",
        "name": "is independent of the hinge penalty stiffness once converged"
      },
      {
        "suite": "summarizeBiaxialPushover",
        "name": "reports the headline numbers straight from the trace"
      },
      {
        "suite": "summarizeBiaxialPushover",
        "name": "ranks hinges by utilisation and honours the limit"
      },
      {
        "suite": "summarizeBiaxialPushover",
        "name": "warns — in words — about model features the hinge element dropped"
      },
      {
        "suite": "summarizeBiaxialPushover",
        "name": "says so when nothing could yield"
      }
    ]
  },
  {
    "module": "axialOnly",
    "group": "Nonlinear",
    "title": "Tension/compression-only active set",
    "integration": false,
    "tests": [
      {
        "suite": "axialOnly — active-set solve",
        "name": "with no limited members it is a plain linear solve"
      },
      {
        "suite": "axialOnly — active-set solve",
        "name": "drops the compressed diagonal of a cross-braced bay"
      },
      {
        "suite": "axialOnly — active-set solve",
        "name": "reversing the load swaps which diagonal is active"
      },
      {
        "suite": "axialOnly — active-set solve",
        "name": "re-activation works — a latched-off iteration would keep both braces off"
      },
      {
        "suite": "axialOnly — active-set solve",
        "name": "the braced bay is stiffer than the same bay with both braces removed"
      },
      {
        "suite": "axialOnly — active-set solve",
        "name": "compression-only struts drop under a pull instead"
      },
      {
        "suite": "axialOnly — active-set solve",
        "name": "equilibrium still holds after members deactivate (ΣR = ΣF)"
      },
      {
        "suite": "axialOnly — active-set solve",
        "name": "response scales linearly while the active set is unchanged"
      },
      {
        "suite": "axialOnly — active-set solve",
        "name": "converges in a handful of iterations"
      },
      {
        "suite": "axialOnly — per-combo active set (analyzeActiveSet)",
        "name": "with no limited members it reproduces analyzeFrame3D combo for combo"
      },
      {
        "suite": "axialOnly — per-combo active set (analyzeActiveSet)",
        "name": "reports one active set per combination, parallel to perCombo"
      },
      {
        "suite": "axialOnly — per-combo active set (analyzeActiveSet)",
        "name": "the active set differs between the gravity combo and the seismic combos"
      },
      {
        "suite": "axialOnly — per-combo active set (analyzeActiveSet)",
        "name": "each combo is solved on its own set — the sets genuinely differ"
      },
      {
        "suite": "axialOnly — per-combo active set (analyzeActiveSet)",
        "name": "superposition is broken — this is why one shared factorization is invalid"
      },
      {
        "suite": "axialOnly — per-combo active set (analyzeActiveSet)",
        "name": "every combo satisfies equilibrium on its own active set"
      },
      {
        "suite": "axialOnly — axialModes helper",
        "name": "collects only the limited members"
      },
      {
        "suite": "meshValidation — axial-mode rules",
        "name": "rejects an axial release on a tension-only member"
      },
      {
        "suite": "meshValidation — axial-mode rules",
        "name": "warns when a node hangs only from limited members"
      },
      {
        "suite": "meshValidation — axial-mode rules",
        "name": "stays quiet for ordinary two-way members"
      }
    ]
  }
]
