// ─────────────────────────────────────────────────────────────────────────
// Generate `src/engine/solverCoverage.ts` — the inventory of every vitest case
// that exercises a SOLVER engine, rendered on the /validation page.
//
// The module list and the parser live in `src/engine/solverCoverageParse.ts`,
// shared with the test that guards this file against drift; this script only
// does the file I/O. Nothing is EXECUTED here, so the manifest cannot claim a
// pass state it never observed — the page says only that these cases exist and
// that CI runs the whole suite, which it does on every PR.
//
// Run:  npm run gen:coverage
// ─────────────────────────────────────────────────────────────────────────
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { SOLVER_MODULES, parseTests } from '../src/engine/solverCoverageParse.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const data = SOLVER_MODULES.map((m) => ({
  module: m.module,
  group: m.group,
  title: m.title,
  integration: !!m.integration,
  tests: parseTests(readFileSync(join(root, 'src/engine', `${m.module}.test.ts`), 'utf8')),
}))
const total = data.reduce((n, m) => n + m.tests.length, 0)

writeFileSync(join(root, 'src/engine/solverCoverage.ts'), `// GENERATED by scripts/genSolverCoverage.mjs — do not edit by hand.
// Regenerate with \`npm run gen:coverage\`; \`solverCoverage.test.ts\` fails if
// this file goes stale, so a solver test cannot be added or renamed without the
// /validation page noticing.
//
// Inventory of every vitest case that exercises a SOLVER engine — a module that
// computes a structural response (assembles and solves equilibrium, an
// eigenproblem, or a time/path integration), plus the bridge feeding them.
// Design checks, load generation, geotech and quantities are covered instead by
// the hand-calc benchmarks in \`validation.ts\`.
//
// These names are read from the test sources. Nothing here observes a pass
// state: what the page claims is that these cases exist and that CI runs them.
import type { SolverGroup } from './solverCoverageParse'

export interface SolverTest { suite: string; name: string }
export interface SolverModuleCoverage {
  /** Engine module, i.e. \`engine/<module>.ts\`. */
  module: string
  group: SolverGroup
  /** What the module solves. */
  title: string
  /** True when the file exercises several solvers together rather than one
   *  module — there is no \`engine/<module>.ts\` behind it. */
  integration: boolean
  tests: SolverTest[]
}

/** Total solver-engine cases in the manifest. */
export const SOLVER_TEST_COUNT = ${total}

export const SOLVER_COVERAGE: SolverModuleCoverage[] = ${JSON.stringify(data, null, 2)}
`)
console.log(`solverCoverage.ts: ${data.length} modules, ${total} tests`)
