// Documentation content — 3D Model Space, the largest tool in the app.
import type { DocTool } from './docsModel'

export const MODEL_TOOLS: DocTool[] = [
  {
    id: 'model-space',
    name: '3D Model Space',
    route: '/model',
    group: 'Analysis & modelling',
    summary: 'The full workflow in one page: build a 3D frame, load it, analyse it, design every member, and print the drawings and reports.',
    basis: 'NSCP 2015 (§203 combinations, §207 wind, §208 seismic, §409/§424 RC), ACI 318-14, AISC 360-16, NDS for timber.',
    sections: [
      {
        id: 'ms-ribbon',
        title: 'Tab ribbon',
        body: 'The full-width row under the header, in three labelled groups plus two utilities. The groups are the sequence — MODEL builds the frame, ANALYSE solves it, RESULTS is where the design and the drawings are read — and each needs the one before it. Display and Projects sit past the divider on the right because they are neither: one changes how the model is drawn, the other opens a different model, and both apply at whatever stage you are at.',
        controls: [
          { kind: 'button', name: '↶ / ↷', what: 'Undo and redo the last model edits — ⌘Z and ⌘⇧Z. Each button says how many steps it has. Ignored while you are typing in a field, where ⌘Z is the browser\'s own undo of the characters.' },
          { kind: 'button', name: '⎙ PDF', what: 'Builds the full calculation report: project data, governing combination, every schedule with its worked solution, drawings and the bill of quantities. Needs a design first.' },
          { kind: 'button', name: 'Guide', what: 'Starts the guided walkthrough, which visits the tabs in the order the ribbon shows them.' },
        ],
      },
      {
        id: 'ms-viewport',
        title: 'Viewport',
        body: 'The 3D scene, with the model\'s name and its autosave badge in the top-left corner and the selection chip under them. Orbit by dragging, pan with Shift+drag, zoom with the scroll wheel. Clicking a member or slab selects it and opens its detail panel. What the scene DRAWS is set on the Display tab, not here.',
        controls: [
          { kind: 'output', name: 'Member tint', what: 'Members are shaded red in proportion to |M| relative to the model maximum for the governing combination — a quick read of where the demand is.' },
          { kind: 'output', name: 'Dashed red sleeve', what: 'Marks a tension/compression-only member that dropped out of the governing combination\'s active set.' },
          { kind: 'output', name: 'Purple arm', what: 'A rigid end offset between a node and the flexible member end.' },
        ],
      },
      {
        id: 'ms-display',
        title: 'Display',
        body: 'The overlays the viewport draws. Its own tab, past the divider on the right of the ribbon because it is not a step in the sequence — and the toggles stay on whatever tab you switch to afterwards, because what the 3D view is drawing is not a property of which tab is open. Each toggle carries its own colour key, and says what it is waiting for when it has nothing to draw yet.',
        controls: [
          { kind: 'choice', name: 'Model — solid / wireframe', what: 'How the model itself is drawn. Wireframe is the skeleton: one line per member from node to node, a marker at each joint, and each panel as its own outline — the analytical model rather than the concrete. Members and panels stay clickable. Switching a force diagram on draws wireframe on its own whatever is picked here, because the ribbon runs along the member axis and would otherwise be inside its own concrete — the choice is not overwritten and comes back when the diagram goes off.' },
          { kind: 'toggle', name: 'Show load diagrams on the model', what: 'Draws the applied loads as arrows on the model. The key below it names the load categories present, one colour each.' },
          { kind: 'toggle', name: 'Show designed footings to scale', what: 'Draws each designed footing at its computed plan size. Overlapping footings are highlighted, which is the cue to switch to a combined footing.' },
          { kind: 'toggle', name: 'Show designed steel connections', what: 'Draws the designed steel joints at their nodes — plates in slate, bolts and welds in gold.' },
          { kind: 'toggle', name: 'Show reinforcement cages', what: 'Draws the designed bars in 3D, colour-coded by role, with the concrete shown see-through. Needs a design first; any detailing decision the cage builder had to make is listed underneath.' },
          { kind: 'choice', name: 'Cages to show', what: 'Which kinds of steel the cage layer draws — beams, columns, slabs, stairs, footings — with the number of cages of each kind placed. A whole building at once is a solid wall of bar; switch the rest off to look at one.' },
          { kind: 'choice', name: 'Force diagram', what: 'Draws N, Vy, Vz, My, Mz or T along every member for the governing combination, with a scale slider. Available once the analysis has run.' },
        ],
      },
      {
        id: 'ms-geometry',
        title: 'Geometry tab',
        body: 'Builds and edits the model. The grid generator is the fastest start; everything can then be edited node by node.',
        controls: [
          { kind: 'field', name: 'Bays X (m, comma-sep)', unit: 'm', what: 'Bay widths along X, e.g. "6,6" for two 6 m bays. Commas separate bays, so the count of numbers is the count of bays.' },
          { kind: 'field', name: 'Bays Z (m)', unit: 'm', what: 'Bay widths along Z, same convention.' },
          { kind: 'field', name: 'Storey heights (m)', unit: 'm', what: 'One number per storey, bottom up, e.g. "3.5,3".' },
          { kind: 'button', name: 'Regenerate grid model', what: 'Replaces the model with a fresh grid from the three fields above. Destructive — it discards manual edits.' },
          { kind: 'output', name: 'Model summary', what: 'Node/member counts split by role, slab and load counts, storey count and heights.' },
          { kind: 'button', name: '+ Add node', what: 'Appends a node; type its X/Y/Z. Y is up.' },
          { kind: 'field', name: 'Node X / Y / Z', unit: 'm', what: 'Node coordinates. Editing one moves everything attached to it.' },
          { kind: 'field', name: 'Node SUP', what: 'Support fixity at the node — none, pin or fixed.' },
          { kind: 'button', name: '✕ (node row)', what: 'Deletes the node and everything attached to it — members, loads and supports.' },
          { kind: 'button', name: '+ Add member', what: 'Connects the two chosen nodes. Disabled when a member already joins them, or when the two ends are the same node.' },
          { kind: 'choice', name: 'Member role', what: 'beam, girder, column or brace. Role drives the design path taken, the span-type table used for serviceability, and how the member is drawn.' },
          { kind: 'choice', name: 'Member I / J', what: 'Start and end nodes. Swapping them reverses the member local axes.' },
          { kind: 'field', name: 'Member LC', unit: 'm', what: 'Clear length, shown for reference.' },
        ],
      },
      {
        id: 'ms-selection',
        title: 'Selection panel',
        body: 'Whatever is selected in the 3D view, at the top of the control panel and on every tab. For a member: role, length, section, the design verdict with its utilisation, the governing forces, and the six force diagrams behind a disclosure. For a slab: panel size, its area loads and the tributary split. It used to live at the foot of the Analysis tab, so clicking a member gave you a chip on the canvas and nothing else unless you were on that one tab.',
        controls: [
          { kind: 'output', name: 'Design', what: 'The verdict from whichever schedule this member landed in — RC or steel, beam or column — with the utilisation where that schedule reports one. Blank until the structure has been designed.' },
          { kind: 'button', name: '▸ Show force diagrams', what: 'Unfolds Mz, My, Vy, Vz, N and T along the selected member for the governing combination. Folded by default because the panel now shows on every tab.' },
          { kind: 'button', name: 'Delete member / Delete slab', what: 'Removes the element and everything attached to it. Asks once — the button arms, then confirms — because it now sits two lines under the thing it deletes rather than at the foot of a tab.' },
        ],
      },
      {
        id: 'ms-member-detail',
        title: 'Selected-member overrides',
        body: 'Appears in the Geometry tab when a member is selected. These are per-member overrides — each one is optional and blank means "use the model default".',
        controls: [
          { kind: 'toggle', name: 'End releases (Fx…Mz, i and j)', what: 'Ticking a box releases that force or moment at that end. Mz is in-plane bending, My out-of-plane. Used for pinned ends and for genuine hinges.' },
          { kind: 'field', name: 'Rigid end offsets (m)', unit: 'm', what: 'Vector from the node to the member end, per axis, per end. The flexible member spans end-to-end and the node-to-end stub is rigid.' },
          { kind: 'field', name: 'Auto rigid-zone factor override', what: 'Per-member override of the model-wide rigid-zone factor. Blank uses the model factor; 0 disables the zone for this member.' },
          { kind: 'field', name: 'Local axis rotation θ (°)', unit: '°', what: 'Rotation about the member axis. Blank means the default (vertical members 90°). Orients section stiffness, rigid zones and the drawn shape.' },
          { kind: 'field', name: 'Lb unbraced length (m)', unit: 'm', what: 'Brace spacing for the §F2 lateral-torsional buckling check on beams and girders. Blank uses the full member length, which is conservative.' },
          { kind: 'choice', name: 'Axial mode', what: 'Both (ordinary), tension-only or compression-only. A limited member that violates its mode is switched off and the model re-solved. This breaks superposition, so every NSCP combination is then solved on its own active set — analysis takes longer.' },
          { kind: 'choice', name: 'End connections (i / j)', what: 'Continuous, Simple (pin — releases My and Mz) or Moment (rigid). Drives both the analysis and the steel connection design.' },
          { kind: 'button', name: 'Delete member', what: 'Removes the member and any loads attached to it.' },
        ],
      },
      {
        id: 'ms-properties',
        title: 'Properties tab',
        body: 'Materials and section sizes. The frame material chosen here decides which design path every member takes.',
        controls: [
          { kind: 'choice', name: 'Frame material', what: 'Concrete, steel or timber. Switching it changes the design engine, the schedules produced, and which panels below apply.' },
          { kind: 'choice', name: 'Column / Girder / Beam family + shape', what: 'AISC shape selection per role, used when the frame material is steel. Family filters the shape list (W, HSS, PIPE…).' },
          { kind: 'field', name: 'Steel Fy / Fu', unit: 'MPa', what: 'Yield and tensile strength for steel members.' },
          { kind: 'choice', name: 'Material source / Species / Grade', what: 'Timber reference values — the NDS species and grade whose allowable stresses are used.' },
          { kind: 'field', name: 'Column / Girder / Beam b, d, h', unit: 'mm', what: 'Rectangular section dimensions per role, for concrete and timber frames.' },
          { kind: 'field', name: 'Slab thickness', unit: 'mm', what: 'Structural slab thickness. Drives self-weight, the shell mesh when shell elements are on, and the slab design.' },
          { kind: 'field', name: "Concrete f′c", unit: 'MPa', what: 'Cylinder strength. Sets Ec = 4700√f′c, so it changes stiffness as well as capacity.' },
          { kind: 'field', name: 'Steel fy', unit: 'MPa', what: 'Reinforcement yield strength.' },
          { kind: 'field', name: 'Clear cover', unit: 'mm', what: 'Cover to the outermost bar; sets the effective depth.' },
          { kind: 'field', name: 'Concrete unit wt γc', unit: 'kN/m³', what: 'Used for member and slab self-weight.' },
          { kind: 'choice', name: 'Main bar ⌀ / Tie / stirrup ⌀', unit: 'mm', what: 'Bar diameters used by the design. The optimizer can try alternatives if that option is enabled.' },
          { kind: 'choice', name: 'Beam design method', what: 'Selects how flexural reinforcement is proportioned.' },
          { kind: 'toggle', name: 'Check beam/girder members as pretensioned bonded', what: 'Adds a prestressed check alongside the ordinary RC design, using the Aps / fpu / e values below.' },
          { kind: 'field', name: 'Aps / fpu / Eccentricity e / f′ci', what: 'Prestressing steel area, tendon strength, tendon eccentricity and concrete strength at transfer.' },
        ],
      },
      {
        id: 'ms-supports',
        title: 'Supports tab',
        body: 'Soil data for the footing design that runs as part of Design all.',
        controls: [
          { kind: 'field', name: 'Soil qa', unit: 'kPa', what: 'Allowable bearing pressure — sizes every spread footing.' },
          { kind: 'field', name: 'Footing depth H', unit: 'm', what: 'Founding depth below grade; sets the overburden credited above the footing.' },
          { kind: 'field', name: 'Soil unit wt γsoil', unit: 'kN/m³', what: 'Unit weight of the soil above the footing.' },
        ],
      },
      {
        id: 'ms-loading',
        title: 'Loading tab',
        body: 'Everything applied to the model. Loads are categorised (D, L, Lr, W, E, T…) and the NSCP combinations are then applied as data over a single factorisation.',
        controls: [
          { kind: 'field', name: 'Default SDL', unit: 'kPa', what: 'Superimposed dead load on every slab — finishes, services, partitions.' },
          { kind: 'field', name: 'Live load', unit: 'kPa', what: 'Slab live load, category L. Combined with the §203.3.1 f₁ factor set in the Analysis tab.' },
          { kind: 'field', name: 'Temperature change ΔT', unit: '°C', what: 'Uniform temperature change. Applied as a self-equilibrating axial prestress PT = EA·α·ΔT, category T.' },
          { kind: 'field', name: 'Ca / Cv', what: 'NSCP §208 seismic coefficients from the site soil profile and zone.' },
          { kind: 'field', name: 'R', what: 'Response modification factor for the lateral system. Also divides the design base shear and multiplies the drift amplification.' },
          { kind: 'field', name: 'I', what: 'Occupancy importance factor. Multiplies the base shear directly, so essential facilities attract a higher demand.' },
          { kind: 'field', name: 'Z (zone) / Nv (near-source)', what: 'Seismic zone factor and near-source factor for zone 4 sites.' },
          { kind: 'field', name: 'V (basic speed)', unit: 'm/s', what: 'Basic wind speed for the §207B directional MWFRS procedure.' },
          { kind: 'field', name: 'Kzt (topographic)', what: 'Topographic factor; 1.0 on flat ground.' },
          { kind: 'field', name: 'Effective wind area', unit: 'm²', what: 'Tributary area for the §207E.4 components-and-cladding wall pressures.' },
          { kind: 'toggle', name: 'regular structure — 0.9·V(T_B) & 0.8·V(T_A) floors', what: 'Applies the §208.5.2.2 Method-B period caps for a regular structure. Unticked treats the structure as irregular and uses the full 100 % V.' },
        ],
      },
      {
        id: 'ms-analysis',
        title: 'Analysis tab',
        body: 'Solver options, then the results. Options change the stiffness the solver assembles, so re-run Analyze after changing any of them.',
        controls: [
          { kind: 'toggle', name: 'Public assembly / garage (f₁ = 1.0)', what: 'NSCP §203.3.1 live-load factor in the combinations. Unticked uses f₁ = 0.5 for ordinary occupancies.' },
          { kind: 'toggle', name: 'P-Δ second-order analysis', what: 'Adds the geometric stiffness from member axial force and iterates. Softens the frame and increases drift; reports convergence.' },
          { kind: 'toggle', name: 'Cracked sections — ACI §6.6.3.1.1', what: 'Applies 0.35Ig to beams and 0.70Ig to columns (concrete only). On by default here; off at the API level so closed-form benchmarks stay gross-section.' },
          { kind: 'toggle', name: 'Shear deformation (Timoshenko)', what: 'Adds shear flexibility Φ = 12EI/(G·As·L²) to the frame element. Matters for deep girders and squat columns.' },
          { kind: 'toggle', name: 'Column bars on all four faces', what: 'Uses a real bar cage in the P–M strain-compatibility check instead of two faces. More realistic and gives a lower balanced moment.' },
          { kind: 'toggle', name: 'Rigid floor diaphragm', what: 'Ties the in-plane lateral DOFs of each storey together. Standard for a cast slab; turn off to study flexible-diaphragm effects.' },
          { kind: 'toggle', name: 'Auto rigid end zones', what: 'Automatic end offsets derived from connectivity, so members are flexible only between faces.' },
          { kind: 'toggle', name: 'Shell elements', what: 'Meshes slab and wall panels as CST+DKT finite elements instead of treating them purely as load sources. Enables the plate-stress and Wood–Armer results.' },
          { kind: 'toggle', name: 'Try alternative bar sizes', what: 'Lets Design and Optimize pick bar diameters (⌀16–⌀32 beams, ⌀20–⌀32 columns) rather than holding the ones set in Properties.' },
          { kind: 'field', name: 'Mesh subdivision n×n', what: 'Shell mesh density per panel. Higher is more accurate and slower.' },
          { kind: 'output', name: 'Governing combination banner', what: 'Which NSCP combination governs, with ΣRy and the model-wide extremes of M, V and N.' },
          { kind: 'output', name: 'Member forces table', what: 'Per-member maxima. The tabs above it switch between the envelope and each individual combination.' },
          { kind: 'output', name: 'Storey drift', what: 'ΔM = 0.7·R·Δs per storey against the §208.5.10 limit (0.025 hs below T = 0.7 s, else 0.020 hs).' },
          { kind: 'output', name: 'Structural irregularities', what: 'Auto-flags against NSCP Tables 208-9/10 — torsional, soft-storey, mass and vertical-geometric — from the E-case drift field and storey weights.' },
          { kind: 'output', name: 'Tension / compression-only members', what: 'Present only when some member has a limited axial mode. Shows the active set per combination, iterations and convergence.' },
        ],
      },
      {
        id: 'ms-modal',
        title: 'Modal tab',
        body: 'Free-vibration properties and linear dynamic response.',
        controls: [
          { kind: 'field', name: 'Number of modes', what: 'How many modes to extract. Ask for enough to accumulate ≥ 90 % mass participation (§208.5.5); the cumulative column turns green at that threshold.' },
          { kind: 'button', name: '〰 Run modal analysis', what: 'Solves the lumped-mass eigenproblem and reports periods, frequencies and effective modal mass per direction.' },
          { kind: 'button', name: 'Mode row', what: 'Click to animate that mode shape in the viewport.' },
          { kind: 'choice', name: 'Ground motion / Direction', what: 'Record and axis for the linear time history.' },
          { kind: 'button', name: '∿ Run time-history', what: 'Modal Newmark-β integration of the selected record.' },
          { kind: 'field', name: 'Floor deflection Δ / Supported weight W', what: 'Inputs to the AISC Design Guide 11 walking-vibration check.' },
        ],
      },
      {
        id: 'ms-pushover',
        title: 'Pushover tab',
        body: 'Nonlinear static capacity curve with plastic hinges.',
        controls: [
          { kind: 'choice', name: 'Push direction', what: 'Axis the lateral load is applied along.' },
          { kind: 'choice', name: 'Lateral pattern', what: 'Distribution of the pushing force up the height.' },
          { kind: 'field', name: 'Concrete ρ (tension)', what: 'Tension steel ratio assumed when computing plastic moments.' },
          { kind: 'field', name: 'Mp scale', what: 'Scales every hinge capacity — useful for sensitivity studies.' },
          { kind: 'toggle', name: 'P–M interaction', what: 'Reduces each hinge\'s plastic moment to Mpc(P) using the member\'s current axial force. Ignoring it is unconservative for columns.' },
          { kind: 'toggle', name: 'P-Δ second order', what: 'Gravity geometric stiffness, which softens the capacity curve and lowers the peak.' },
          { kind: 'output', name: 'Capacity curve', what: 'Base shear against roof displacement, with the hinge formation sequence marked along it.' },
        ],
      },
      {
        id: 'ms-biaxial-pushover',
        title: 'Pushover tab — biaxial (skew) pushover',
        body: 'A second pushover on the same tab, and a different idealisation. The one above reduces the '
          + 'building to an equivalent plane frame and gives each member end a hinge that bends about ONE axis. '
          + 'This one runs on the real 3-D model with no reduction, and each hinge carries a moment vector whose '
          + 'two bending axes yield on a single coupled surface. That is what makes a push at an arbitrary plan '
          + 'angle meaningful: at 45° a corner column can sit at 0.8·Mpy AND 0.8·Mpz, which two independent 1-D '
          + 'hinges would call elastic and the real section calls well past yield.',
        controls: [
          { kind: 'field', name: 'Push angle in plan', unit: '°', default: '45', what: 'Direction of the lateral push measured from +X toward +Z. 0° and 90° are the principal directions; intermediate angles bend every column about both local axes at once, which is the case this analysis exists for.' },
          { kind: 'field', name: 'Target roof drift', unit: '% of H', default: '4', what: 'How far the control node is pushed, as a fraction of the total frame height. The push is displacement-controlled, so the curve can descend past its peak instead of stopping there.' },
          { kind: 'field', name: 'Displacement steps', default: '40', what: 'Number of increments the target drift is reached in. More steps give a smoother capacity curve and make convergence easier when many hinges yield at once; the result panel reports any step that fell short.' },
          { kind: 'choice', name: 'Yield surface', default: 'Bresler contour', what: 'Which surface couples the two bending axes. Bresler is the ACI load contour for reinforced-concrete columns and takes axial load through the uniaxial P–M chords. Orbison is the standard fitted surface for compact steel I-shapes and carries the axial term inside the surface itself.' },
          { kind: 'field', name: 'Contour exponent α', default: '2', what: 'Shape of the Bresler contour. 1 is the conservative linear chord, about 1.5 the usual reinforced-concrete fit, 2 the ellipse. Larger values weaken the coupling toward independent axes, but above roughly 6 the surface approaches a sharp-cornered box and the hinge return map stops converging.' },
          { kind: 'toggle', name: 'P–M interaction (biaxial)', default: 'on', what: 'Reduces both hinge capacities for the member\u2019s current axial force. Turning it off leaves the pure-bending capacities, which overstates column strength.' },
          { kind: 'button', name: 'Run biaxial pushover', what: 'Runs the skew push in the background worker. Concrete ρ and Mp scale are shared with the pushover settings above rather than duplicated.' },
          { kind: 'output', name: 'Peak base shear', unit: 'kN', what: 'Largest total lateral force carried, measured on whichever global axis takes the larger share of the push.' },
          { kind: 'output', name: 'Converged at every step', what: 'Whether every increment reached the residual tolerance, and the worst residual over the trace. A push that fell short is flagged rather than quietly reported, because the capacity beyond that point is not trustworthy.' },
          { kind: 'output', name: 'Most-utilised hinges', what: 'The worst hinges by demand/capacity on the yield surface, with My and Mz about the member\u2019s own local axes, the axial force, and the accumulated plastic rotation.' },
          { kind: 'output', name: 'Warnings', what: 'Plain-language cautions: member end releases and rigid offsets that the hinge element cannot represent (the run is then stiffer and stronger than the real frame), steps that did not converge, a collapse mechanism, or a model where nothing could yield.' },
        ],
      },
      {
        id: 'ms-nonlinear',
        title: 'Nonlinear tab',
        body: 'Nonlinear time history. Two plasticity models are offered; they differ in how the structure is idealised, not just in numerics.',
        controls: [
          { kind: 'choice', name: 'Plasticity model', what: 'Member-end plastic hinges (default) condenses the building to an equivalent plane frame with a hinge at each member end — no shear-building assumption. Shear building (storey springs) reduces each storey to a single hysteretic spring, which is faster but assumes shear-type behaviour.' },
          { kind: 'choice', name: 'Ground motion / Direction', what: 'Excitation record and axis.' },
          { kind: 'field', name: 'Peak ground accel', unit: 'g', what: 'Scales the whole record so its peak equals this value — the primary intensity control.' },
          { kind: 'field', name: 'Frequency / Duration', what: 'Shape the synthetic record when one is selected.' },
          { kind: 'field', name: 'Damping ζ', what: 'Rayleigh damping ratio at the two anchor frequencies.' },
          { kind: 'field', name: 'Post-yield ratio b', what: 'Hinge hardening as a fraction of the member EI/L. Negative values soften.' },
          { kind: 'output', name: 'Response summary', what: 'Equivalent-frame period and condensation summary, hinges yielded / total, peak base shear against the elastic demand, peak roof drift, dissipated energy and Newton convergence.' },
          { kind: 'output', name: 'Force-reduction ratio', what: 'Peak inelastic base shear over the elastic demand. Labelled explicitly as not a code R factor.' },
          { kind: 'output', name: 'Yielded hinges table', what: 'Worst hinges ordered by plastic rotation. When nothing yields the panel says so — an elastic outcome is a result, not a blank.' },
        ],
      },
      {
        id: 'ms-design',
        title: 'Design tab',
        body: 'Runs the design pipeline and shows every schedule. Rows expand to a full worked solution with drawings.',
        controls: [
          { kind: 'button', name: '🏗 Design structure', what: 'Designs every member and footing for the governing combination of each element.' },
          { kind: 'button', name: '🏁 Optimize design', what: 'Iterates section sizes until every check passes, then reports the converged model.' },
          { kind: 'button', name: 'Schedule row', what: 'Expands to the step-by-step worked solution, force diagrams, rebar elevation and cross-section for that member.' },
          { kind: 'button', name: 'Schedules / Bill of Quantities / Construction Schedule', what: 'Sub-tabs of the Design results.' },
          { kind: 'output', name: 'Serviceability card', what: 'NSCP §424.2 computed deflection per RC beam — Ig, Icr, Branson Ie, Mcr vs Ma, immediate and long-term deflections against L/360 and L/240, and the Table 409.3.1.1 minimum thickness. A row passes on either route: h ≥ hMin, or the computed check.' },
          { kind: 'output', name: 'δ chip', what: 'On each beam row: computed total deflection against the L/240 limit, green or red.' },
          { kind: 'output', name: 'Pass chip', what: 'Per-schedule "all passed" or "N failed" tally.' },
        ],
      },
      {
        id: 'ms-plans',
        title: 'Plans tab',
        body: 'Drawing sheets generated from the model and the completed design.',
        controls: [
          { kind: 'output', name: 'Framing plan', what: 'Per-storey plan with grid bubbles, member marks, slab span-direction symbols and slab marks. Bays with no slab are crossed.' },
          { kind: 'output', name: 'Foundation plan', what: 'Footing layout with marks, tie beams and founding elevations.' },
          { kind: 'output', name: 'Footing detail sheet', what: 'Bar-mat plan and Section A-A per footing type.' },
        ],
      },
    ],
  },
]
